### ISSUE TITLE
人物面板显示的物品等级不准确

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#10]
满级后获取的物品没问题，满级前获取的物品很不准确
神器副手没有加上圣物提供的装等

**Comment by siweia** [comment]
你观察目标时，副手该是什么就是什么，本身系统也没有加上圣物，所以不考虑。
满级前不准确的是什么，观察目标还是自身，还是背包，要表述清楚

**Comment by Solor** [comment]
比如这个饰品，我是满级前获得的，人物面板的饰品格子显示162，实际上应该是154，基本上满级前获得的装备都有这个问题，满级后获得的都正常。


![wowscrnshot_080818_125430](https://user-images.githubusercontent.com/156806/43823727-9c32e99a-9b22-11e8-86e7-2fb960ce44f2.jpg)

**Comment by Solor** [comment]
可以参考这个[库](https://www.wowace.com/projects/libitemupgradeinfo-1-0)
用它的升级表获取的低级物品装等都是准确的

**Comment by siweia** [comment]
这个物品放在背包的话，装等是正确的吗

**Comment by Solor** [comment]
找到原因了，是我忘了删这个导致获取的装等不对 🤣 
`ITEM_LEVEL = "|cff00ffffilvl: %d|r"`
`ITEM_LEVEL_ALT = "|cff00ffffilvl: %d (%d)|r"`
