### ISSUE TITLE
PlayerChoiceUI这类有黄色材质背景的地方，为什么文字不直接使用黑色呢？

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#102]
原始的淡黄色和白色文字不管加不加阴影观感都很差，为什么不直接使用黑色呢？

![QQ图片20201017224336](https://user-images.githubusercontent.com/156806/96336413-50817900-10cb-11eb-95e4-3f19c0e9a933.png)

![QQ图片20201017224416](https://user-images.githubusercontent.com/156806/96336420-56775a00-10cb-11eb-9ded-a3278f8911db.png)

![QQ图片20201017224857](https://user-images.githubusercontent.com/156806/96336433-83c40800-10cb-11eb-8ea2-c1e89346284c.png)

**Comment by siweia** [comment]
所有的都是为了阴影服务
