### ISSUE TITLE
addonlist里非当前角色启用的插件无法以灰色显示

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#105]
以前是正常的，非当前角色启用的插件是灰色的勾，9.0以后失效了，所有勾都是职业颜色。

**Comment by siweia** [comment]
关闭美化后是正常的吗？

**Comment by siweia** [comment]
我无法复现这种查看非当前角色插件启用的情况，除非在角色选择面板

**Comment by Solor** [comment]
我搞错了，当前角色进入游戏后是看不到其他角色的插件启用情况的 👌
