### ISSUE TITLE
多面硬币这个玩具的冷却时间不显示

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#107]
[多面硬币](https://www.wowhead.com/item=128807/coin-of-many-faces)是24h冷却，正常情况下它的冷却显示是正常的
在万圣节期间多面硬币的冷却时间会缩短，使用后不显示冷却时间，按照wowhead的评论，万圣节期间的冷却时间是1h，不清楚为啥会不显示时间

**Comment by siweia** [comment]
插件都关了不是一样的，这应该问暴雪
