### ISSUE TITLE
/mm command. No 简体中文, 繁體中文, enUS locale

### ISSUE THREAD

**Issue by jsaneu** [siweia/NDui#109]
Should the command `/mm` work with a locale other than 简体中文, 繁體中文, enUS? Using esES locale, the command `/mm` does not work. No error messages.
Using enUS locale, it works perfectly.

Great UI, thank you!

**Comment by siweia** [comment]
It seems like cmd `/mm` is occupied in locale esES by blizzard, you can use cmd `/mm 1` to place world marker.
