### ISSUE TITLE
...Modules\Skins\Blizzard\FrameXML\ObjectiveTracker.lua:12: attempt to call method 'SetNormalTexture' (a nil value)

### ISSUE THREAD

**Issue by JourneyOver** [siweia/NDui#113]
This error happens whenever you get a quest that has a "use" item with it that is being tracked.
![BPAhCGD](https://user-images.githubusercontent.com/13910285/100120145-3ad74000-2e3d-11eb-9aab-49e05fb08cee.png)

```
...Modules\Skins\Blizzard\FrameXML\ObjectiveTracker.lua:12: attempt to call method 'SetNormalTexture' (a nil value)
Count: 1

Call Stack:
[string "@AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `SetNormalTexture'
[string "@AddOns\NDui\Modules\Skins\Blizzard\FrameXML\ObjectiveTracker.lua"]:12: in function <...Modules\Skins\Blizzard\FrameXML\ObjectiveTracker.lua:7>
[string "@AddOns\NDui\Modules\Skins\Blizzard\FrameXML\ObjectiveTracker.lua"]:31: in function <...Modules\Skins\Blizzard\FrameXML\ObjectiveTracker.lua:29>
[string "=[C]"]: in function `SetBlockHeader'
[string "@AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua"]:375: in function `func'
[string "@AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua"]:243: in function `EnumQuestWatchData'
[string "@AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua"]:471: in function `Update'
[string "@AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1370: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1323>
[string "=[C]"]: ?
[string "@AddOns\!KalielsTracker\KalielsTracker.lua"]:566: in function `ObjectiveTracker_Update'
[string "@AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:835: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:833>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@AddOns\!KalielsTracker\Modules\Filters.lua"]:91: in function <AddOns\!KalielsTracker\Modules\Filters.lua:84>
```

not sure if issue on your side or on the side of Kaliel's Tracker, but I have made a [report](https://www.curseforge.com/wow/addons/kaliels-tracker/issues/501) on their addon page as well just encase.

**Comment by JourneyOver** [comment]
Well I hope you are able to fix this issue on this side as the dev of said addon above doesn't seem to want to add support for anymore UI's.. :/

**Comment by siweia** [comment]
https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Skins/Blizzard/FrameXML/ObjectiveTracker.lua#L8
Add a line under line 8:
`if not button.SetNormalTexture then return end`

KalielsTracker overrides default UI element, that's why the `SetNormalTexture` become not available.

**Comment by siweia** [comment]
I might add an option to turn off the objective tracker skin later as well.

**Comment by JourneyOver** [comment]
Well thanks for the code line so that I can stop the taint for now, but yes an option would be lovely for instances like this.
