### ISSUE TITLE
同时有组队按钮和物品按钮的任务组队按钮没有正确美化

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#115]
![WoWScrnShot_112420_124048](https://user-images.githubusercontent.com/156806/100271229-45184c00-2fad-11eb-8dd6-a78866cdb7da.png)

**Comment by siweia** [comment]
哪个地图的任务来着，之前遇到过，没管它

**Comment by Solor** [comment]
https://www.wowhead.com/quest=60366/wanted-darkwing
