### ISSUE TITLE
[Request] Actionbar border equipped color.

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#117]
So currently the UI action-bar skin does not support if you put something you have equipped on your action-bars to change the border color to green like blizzard does. Example below.

NDui.
![image](https://user-images.githubusercontent.com/40672673/100849323-661aea00-3450-11eb-979a-9ec30177aaeb.png)

Blizzard.
![image](https://user-images.githubusercontent.com/40672673/100849423-8b0f5d00-3450-11eb-83f0-dc4c85571bb1.png)

**Comment by siweia** [comment]
Its intended atm.
