### ISSUE TITLE
[bug] attempt to index local 'self' (a number value)

### ISSUE THREAD

**Issue by JourneyOver** [siweia/NDui#120]
Error Message:
```
AddOns\NDui\Core\Functions.lua:357: attempt to index local 'self' (a number value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\NDui\Core\Functions.lua"]:357: in function `StripTextures'
[string "@AddOns\NDui\Core\Functions.lua"]:361: in function `StripTextures'
[string "@AddOns\NDui\Modules\Skins\Blizzard\Blizzard_Communities.lua"]:321: in function `func'
[string "@AddOns\NDui\Modules\Skins\Skins.lua"]:33: in function `func'
[string "@AddOns\NDui\Init.lua"]:23: in function <AddOns\NDui\Init.lua:18>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:777: in function `Communities_LoadUI'
[string "@FrameXML\UIParent.lua"]:1059: in function `ToggleCommunitiesFrame'
[string "@FrameXML\UIParent.lua"]:914: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>
```

I know kind of what causes it, but I'm not sure on how to go about fixing it myself. there is a conflict between NDui and Zygor Guides Viewer when opening "Guild & Communities" for the first time or after a /reload. Something to do with this line https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Core/Functions.lua#L357

It doesn't happen when NDui is only enabled and it doesn't happen when Zygor Guides Viewer is only enabled, it only happens when both of them are enabled at the same time.

**Comment by siweia** [comment]
Same as your previous issue, zygor overrides blizzard ui elements, and causes the error.

**Comment by JourneyOver** [comment]
@siweia yes I know this as I said I know what causes it, I just don't know how to fix it.

**Comment by JourneyOver** [comment]
@siweia Sadly your fix didn't actually fix the issue, as it's still happening :/

```
AddOns\NDui\Core\Functions.lua:357: attempt to index local 'self' (a number value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\NDui\Core\Functions.lua"]:357: in function `StripTextures'
[string "@AddOns\NDui\Core\Functions.lua"]:361: in function `StripTextures'
[string "@AddOns\NDui\Modules\Skins\Blizzard\Blizzard_Communities.lua"]:322: in function `func'
[string "@AddOns\NDui\Modules\Skins\Skins.lua"]:33: in function `func'
[string "@AddOns\NDui\Init.lua"]:23: in function <AddOns\NDui\Init.lua:18>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:777: in function `Communities_LoadUI'
[string "@FrameXML\UIParent.lua"]:1059: in function `ToggleCommunitiesFrame'
[string "@FrameXML\UIParent.lua"]:914: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>
```

main thing it seems to have done was change the line:
```[string "@AddOns\NDui\Modules\Skins\Blizzard\Blizzard_Communities.lua"]:321: in function `func'```
to now ```[string "@AddOns\NDui\Modules\Skins\Blizzard\Blizzard_Communities.lua"]:322: in function `func'```

**Comment by siweia** [comment]
https://github.com/siweia/NDui/commit/8f1d4ee03dc2ef7989ecb922624491242fcd1d45
Try to rename all the `dialog` into `CommunitiesSettingsDialog`.

**Comment by JourneyOver** [comment]
@siweia Nope sadly that does not seem to work either :/ it's just throws the same error as above with the 322 one. The only thing that technically stops the error is just commenting out line 322 but then the rest of that is kinda pointless.. heh if this doesn't get fixed it's whatever I guess, just kind of annoying have to deal with an error whenever I decide to open the Guild & Communities screen on first login or whenever I reload the UI.

**Comment by siweia** [comment]
Send me a copy of your zygor.

**Comment by JourneyOver** [comment]
@siweia I sent it to your email (hopefully the correct one unless you changed your email at some point between the last time I had emailed you and now) I just sent the addon, dunno if you needed the saved variables as well for zygor, if so let me know and I'll send them over as well.

**Comment by JourneyOver** [comment]
@siweia can say your latest update has stopped the lua error now ^^
