### ISSUE TITLE
Custom Unit List Confusion?

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#122]
So I am trying to add an NPC to the Custom Unit List to be colored, though it says to enter the name directly and I have yet it is not coloring that NPC as a custom unit? I have tried the name, npcID and the name with no spaces, yet nothing is happening. Is it possible you can just make it accept just npcID?

![image](https://user-images.githubusercontent.com/40672673/101355225-488cbc80-3864-11eb-96cb-9bf5dde627de.png)

**Comment by siweia** [comment]
Because I use KEY SPACE between different names, once a name has a space in the middle, it would treat the name as two mobs.

**Comment by siweia** [comment]
I would change the way to divide npcs, and npc id will be acceptable as well.

**Comment by Kkthnx** [comment]
Okay, thank you. Sorry for the confusion!
