### ISSUE TITLE
WeakAuras皮肤的问题

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#123]
时不时的会有某个图标的背景覆盖到图标上

![QQ图片20201208022558](https://user-images.githubusercontent.com/156806/101370395-8db0fd00-38fd-11eb-9546-53e931a2ce08.png)

这里加入 `f.bg:SetFrameStrata('BACKGROUND')` 能解决
https://github.com/siweia/NDui/blob/c4a0b3e8483bc0d63f75e61cae34dd8ac5fcf7b8/Interface/AddOns/NDui/Modules/Skins/AddOns/WeakAuras.lua#L43

**Comment by Solor** [comment]
另外边框阴影的层级高于冷却数字，同样方法也能解决

**Comment by siweia** [comment]
f.bg.__shadow 这个没必要吧，正常应该f.bg降低了，shadow就会自动降低

**Comment by Solor** [comment]
嗯，是的，我看错了，降低f.bg的层级就可以了
