### ISSUE TITLE
ChatBar点击加入世界频道的问题

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#124]
英文客户端应该加入 `BigfootWorldChannel`

```local channelName, channelID, channels = GetLocale() == "zhCN" and "大脚世界频道" or "BigfootWorldChannel"```

https://github.com/siweia/NDui/blob/215bf0fffa768bb0fdf2ce7eaaab8b7c8f4d0a4b/Interface/AddOns/NDui/Modules/Chat/Chatbar.lua#L85

**Comment by siweia** [comment]
全世界只有国服用大脚世界频道。不管你什么客户端，大脚世界频道名字都是一样的简体字。你用别的语言或者繁体字，都不会是同一个频道

**Comment by Solor** [comment]
英文客户端的 BigfootWorldChannel 和国服客户端的 大脚世界频道 是共通的
英文客户端是无法加入 大脚世界频道 的

**Comment by siweia** [comment]
不考虑，你可以自己加。
