### ISSUE TITLE
objectivetracker的心能栏位置判断有问题

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#126]
我的objectivetracker是在右侧的，但是心能栏点开也在右侧

![Wow 2020-12-10 06-28-06](https://user-images.githubusercontent.com/156806/101678440-107ab900-3ab2-11eb-9fbf-dca5128cf4bd.jpg)

**Comment by siweia** [comment]
我这里试了都正常啊

**Comment by Solor** [comment]
是UI缩放引起的
如果我使用正常的UI缩放，也就是那个 `GetBestScale()` 得到的值，就正常
但是我的分辨率是 3840*2160，默认的最佳分辨率什么都看不清，必须要 *2
然后这个位置判断就不对了

![Wow 2020-12-10 20-51-15](https://user-images.githubusercontent.com/156806/101756968-b4a04680-3b2a-11eb-9b58-47981937bde9.jpg)

**Comment by siweia** [comment]
https://github.com/siweia/NDui/blob/7702b7e63ad492417415d9e2357f777dfa738347/Interface/AddOns/NDui/Modules/Skins/Blizzard/FrameXML/ObjectiveTracker.lua#L111
你把这个frame改成ScenarioBlocksFrame看看

**Comment by Solor** [comment]
这样不行
我自己是这样弄的
```
local function GetMawBuffsAnchor(frame)
	local center = frame:GetCenter()
	if center and center < C.ScreenWidth/2 * C.Mult then
		return "LEFT"
	else
		return "RIGHT"
	end
end
```
`*C.Mult`能获得真实的尺寸，然后再判断位置就正确了

**Comment by siweia** [comment]
这个时候你的screenwidth是多少，以及ScenarioBlocksFrame:GetCenter的数值

**Comment by Solor** [comment]
这是使用默认的uiscale
![1](https://user-images.githubusercontent.com/156806/101779796-d3620580-3b49-11eb-80b2-54c421d29b43.png)

这是我用的uiscale*2
![2](https://user-images.githubusercontent.com/156806/101779950-02787700-3b4a-11eb-8baf-8cd5a6e50e26.png)

**Comment by siweia** [comment]
你再看看GetScreenWidth和GetPhysicalScreenSize

**Comment by Solor** [comment]
uiscale = 1
![4](https://user-images.githubusercontent.com/156806/101885368-268d9400-3bee-11eb-9689-685374890d64.png)

uiscale * 2 
![3](https://user-images.githubusercontent.com/156806/101885403-34431980-3bee-11eb-94f0-c303ce2594b2.png)
