### ISSUE TITLE
Nameplate Request

### ISSUE THREAD

**Issue by Urguk** [siweia/NDui#129]
I would like to be able either force hide an NPC or force show NPC.

**Comment by siweia** [comment]
Nameplate visibility is controlled by blizzard, you can't hide or show a npc's nameplate specifically.
The cmd `/run SetCVar("nameplateShowFriendlyNPCs", 0)` can hide all npc nameplates when you have friendly nameplates on.
`/run SetCVar("nameplateShowFriendlyNPCs", 1)` as opposite.

**Comment by Urguk** [comment]
I don't think that is a true statement as other UI's I have seen are doing
it like Plater and ElvUi. I'm able to enter an NPC # or name and say hide
and it hide for example Horde Peon.

**Comment by siweia** [comment]
I can't even imagine a way to achieve this feature.
I suggest you can use plater as a replacement.
