### ISSUE TITLE
buttonrange 能否对 objectivetracker 上的物品图标也起作用？

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#13]

**Comment by siweia** [comment]
那个物品图标不靠谱，建议使用这个https://github.com/p3lim-wow/ExtraQuestButton

**Comment by siweia** [comment]
https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Plugins/Accessibility/ExtraQuestButton.lua

**Comment by Solor** [comment]
👍
