### ISSUE TITLE
求帮忙

### ISSUE THREAD

**Issue by nanjuekaien1** [siweia/NDui#130]
button.count = button:CreateFontString(nil, "ARTWORK")
	button.count:SetPoint("TOPRIGHT", -1, -3)
	button.count:SetFont("Interface\\AddOns\\NDui\\Media\\ROADWAY.TTF", 15, DB.Font[3])

	button.timer = button:CreateFontString(nil, "ARTWORK")
	button.timer:SetPoint("TOP", button, "BOTTOM", 1, 2)
	button.timer:SetFont("Interface\\AddOns\\NDui\\Media\\ROADWAY.TTF", 15, DB.Font[3]) --256位置；257 BUFF字体；更换路径
我把BUFF的字体修改了调用指定的字体，每次RL后就恢复到默认字体。是那里还需要改吗？

**Comment by siweia** [comment]
210，211

**Comment by nanjuekaien1** [comment]
谢谢。。。。就是没看到这个。。。
