### ISSUE TITLE
申请整合Neavo写的Sora's Threat

### ISSUE THREAD

**Issue by nanjuekaien1** [siweia/NDui#135]
[Sora's Threat.zip](https://github.com/siweia/NDui/files/5799758/Sora.s.Threat.zip)
这是找到的8.0的版本。

**Comment by siweia** [comment]
没卵用，也没兴趣

**Comment by nanjuekaien1** [comment]
那我 装个仇恨插件吧，在正式服玩了复仇，不想多装个插件。。。

**Comment by siweia** [comment]
不要用怀旧服的思想玩正式服。正式服压根不用管仇恨的，一般不会OT。
如果自己仇恨不稳，你装这种插件也没有用。正式服怪物仇恨的反应比怀旧服灵敏，看血条颜色就好了。

**Comment by nanjuekaien1** [comment]
明白了，我是怕下本被人OT了，不好看。
