### ISSUE TITLE
Bag filter request

### ISSUE THREAD

**Issue by Urguk** [siweia/NDui#149]
Could a filter be added for Relic just like you did for Anima items. Thanks and great work on this UI best ever.

**Comment by Kkthnx** [comment]
I think this has to be done by a manual list or by tooltip scanning. I also looked for any globals for "Korthian Relics" but could not find one.

@siweia Have you thought about formatting the filters in the bags to for example stack 4 filters high then branch off to the left and start stacking again. This would allow more filters to be present. This is done with https://www.curseforge.com/wow/addons/cargbags-nivaya-mop-update

**Comment by Urguk** [comment]
being able to add more filters would be great.
