### ISSUE TITLE
任务追踪栏的一个小问题

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#16]
有进度条的世界任务，在进度条已经显示的情况下，如果重载界面，会造成进度条以及右侧图标出现双份

![issue](https://user-images.githubusercontent.com/156806/45599571-7f2a5280-ba20-11e8-81d3-2985490961f3.jpg)

**Comment by siweia** [comment]
老毛病了，不过我这里只会加深背景，没有发现双份。
