### ISSUE TITLE
有什么办法可以对团队框架的debuffs做过滤吗

### ISSUE THREAD

**Issue by LeeJuly30** [siweia/NDui#168]
有什么办法可以对团队框架的debuffs做过滤吗
团队框架好像有2个地方显示debuff  一个是左下角按暴雪的逻辑显示3个  一个是右边显示一个 类似bigdebuffs  可以控制右边的这个做一个 黑名单 / 白名单的过滤吗？ 插句题外话 bigdebuffs对于ndui的团队框架好像没用 - -
thx~

**Comment by siweia** [comment]
研究一下控制台，团队框架分类下很多齿轮都可以点开设置

**Comment by LeeJuly30** [comment]
![WoWScrnShot_040422_153537](https://user-images.githubusercontent.com/31088072/161495895-1c49e28d-f6d5-4f70-b5e3-21ac16a26a21.jpg)
研究过了 但是上面这个case现有好像没法解决  身上有点燃 霜环的debuff 点燃是先触发的导致霜环的debuff没显示  这样的竞技场的时候一些队友吃一些控制容易看不到
![WoWScrnShot_040422_154121](https://user-images.githubusercontent.com/31088072/161496766-5fc3ccdb-fa98-4511-b192-c4b06d777f2a.jpg)
这个界面配置的debuff必须是地下城和团本的

**Comment by siweia** [comment]
这就没法了，因为你可以驱散的法术会优先显示。

**Comment by LeeJuly30** [comment]
可以加一个选项给这个debuffs加一些黑/白名单？  就先姓名版的debuff一样？
