### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#17]
能否加入聊天栏上ctrl+左键点击人名直接举报玩家骚扰的功能，默认的举报功能会弹出面板要选择理由再确认太麻烦了~
以前用的是下面这段，但是8.0以后举报系统有改动就失效了 😢 

```local _ChatFrame_OnHyperlinkShow = ChatFrame_OnHyperlinkShow;
function ChatFrame_OnHyperlinkShow (chatframe,link,text,button)
	if IsControlKeyDown() then
		local line = string.match(link,"player:[^:]+:(%d+):");
			if line then
				ReportPlayer("spam",line);
			return;
		end
	end
	return _ChatFrame_OnHyperlinkShow (chatframe,link,text,button);
end

**Comment by siweia** [comment]
CTRL+左键现在是邀请入会的功能，而且现在这个版本举报没什么用，不会自动把这个人之前的聊天内容过滤掉。所以不考虑加这个。
现在举报需要通过右键菜单来获取一个playerLocation，所以最多实现在右键菜单加个快速举报的选项。你可以参考之前的我删除的
https://github.com/siweia/NDui/blob/e7fbed70666c19c41933ae735d216dce234593d3/Interface/AddOns/NDui/Plugins/Accessibility/TinyMenu.lua
