### ISSUE TITLE
TBC-SortBag ignore

### ISSUE THREAD

**Issue by Delte** [siweia/NDui#170]
is there any posibility activate ignore SortBag for specific bags, atleast with script command? as i see ignore part is disabled in lua.
when i edited my SortBag.lua its work well with script command.

**Comment by siweia** [comment]
Which specific? The ignore part is only available for blizzard bags index. In ndui, all bag slots merge into one, that is the reason I commented out the ignore code in there.

**Comment by Delte** [comment]
https://github.com/siweia/NDui/blob/9f559fc3bfe6929cf38c60cb6a673c257dc270e4/Interface/AddOns/NDui/Modules/Bags/SortBags.lua#L15
if you uncommented this part it works with 
`/run SetBagSlotFlag(bagId, LE_BAG_FILTER_FLAG_IGNORE_CLEANUP, Boolean)`
`/run SetBankBagSlotFlag(bagId, LE_BAG_FILTER_FLAG_IGNORE_CLEANUP, Boolean)`

**Comment by siweia** [comment]
As I said, this is meanless in NDui. It only makes sense on default separate bags.
