### ISSUE TITLE
[Feature] Add support for special combinations on RaidFrame ClickCast

### ISSUE THREAD

**Issue by lbagic** [siweia/NDui#174]
Currently it is possible to just use [special key] + [mouse button]
Could you consider also adding combinations to the list? E.g. [special key] + [special key] + [mouse button]
Its the only thing preventing me from ditching healbot (or some other click-grid ui), and I'd love to ditch it in favor of NDui, its the best complete ui addon I've ever used. Replaces so many other addons.

It would also be useful if text's were shorter ~ Example:
"LMB" instead of "Left Mouse Button"
"RMB" instead of right
"MMB" instead of middle
"MB4" instead of "Mouse button 4"
"MB5" instead of button 5
Because currently text overflows in both spell list and key selection dropdown

**Comment by siweia** [comment]
Try 6.24.6 d954314a40a1cd6be071e9125de4b520746a0d3e.
