### ISSUE TITLE
WotLK / RaidTank Frames

### ISSUE THREAD

**Issue by merlinmage** [siweia/NDui#179]
(Using NDui Classic 3.1.1)

Hello,

in raids, tank frames were covered by NDui Plus until this feature got removed a couple of days ago.
Since it isn't really stated this change was done, I wanted to request that you maybe add this feature in the Mainline NDui? This would be a huge plus!

All the Best,
merlin

**Comment by siweia** [comment]
It seems useless in retail, and even in the upcoming wotlk. Because we can have the raid roles for all raid members.

**Comment by merlinmage** [comment]
I know actually some people who use these frames, but it cant be helped then I guess. Cheers for answering though!
