### ISSUE TITLE
Quest Tracking on World Map

### ISSUE THREAD

**Issue by Capturedlak3** [siweia/NDui#180]
Greetings

WIth Wotlk i found your UI and found it super cool. but one thing im missing a quest tracking like in retail that show on the world map where to go for the quest with the round numbers. i tried many other addons like questi but none of them seemd to work with that ui. i really like the ui and want to use it for wotlk so i hope you can fix that as fast as possible i would love to see that. thanks

**Comment by siweia** [comment]
No need to fix anything. Questie works fine for me.
Make sure all your addons get updated.
