### ISSUE TITLE
Crashing after today's update, version 3.4.0.45506 

### ISSUE THREAD

**Issue by AceHao** [siweia/NDui#181]

**Comment by erimid** [comment]
Seeing the same issue here.

**Error 1:**

Message: Interface\AddOns\NDui\Core\Functions.lua:297: attempt to index local 'self' (a nil value)
Time: Fri Sep  9 20:29:17 2022
Count: 1
Stack: Interface\AddOns\NDui\Core\Functions.lua:297: attempt to index local 'self' (a nil value)
[string "@Interface\AddOns\NDui\Core\Functions.lua"]:297: in function `HideObject'
[string "@Interface\AddOns\NDui\Modules\ActionBar\Bars\MicroMenu.lua"]:140: in function `MicroMenu'
[string "@Interface\AddOns\NDui\Modules\ActionBar\Bars\Bar1.lua"]:146: in function `OnLogin'
[string "@Interface\AddOns\NDui\Init.lua"]:117: in function `func'
[string "@Interface\AddOns\NDui\Init.lua"]:23: in function <Interface\AddOns\NDui\Init.lua:18>

Locals: self = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'self' (a nil value)"
B = <table> {
 AddTooltip = <function> defined =[C]:-1
 AuraIcon = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:637
 SetGradient = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:491
 ReskinDropDown = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:969
 GetNPCID = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:94
 GetNPCName = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:263
 CreateSD = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:525
 ScanTip = NDui_ScanTooltip {
 }
 CopyTable = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:100
 CreateBD = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:557
 ReskinNavBar = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1091
 ToggleFriends = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1725
 CreateGradient = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:565
 ReskinMinMax = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1253
 PixelIcon = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:615
 CreateColorSwatch = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1643
 RegisterModule = <function> defined @Interface\AddOns\NDui\Init.lua:56
 CreateAndUpdateBarTicks = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:748
 CreateGear = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:645
 Reskin = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:827
 ResetTabAnchor = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:892
 UnitColor = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:139
 Dummy = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:289
 ClassIconTexCoord = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:721
 UpdateMoneyDisplay = <function> defined @Interface\AddOns\NDui\Modules\Skins\Blizzard\FrameXML\MailFrame.lua:4
 IsBase64 = <function> defined @Interface\AddOns\NDui\Libs\LibBase64.lua:143
 RegisterEvent = <function> defined @Interface\AddOns\NDui\Init.lua:28
 Decode = <function> defined @Interface\AddOns\NDui\Libs\LibBase64.lua:97
 ReskinInput = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1032
 HelpInfoAcknowledge = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:371
 Encode = <function> defined @Interface\AddOns\NDui\Libs\LibBase64.lua:35
 ShowHelpTip = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:385
 ReskinCheck = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1117
 CooldownOnUpdate = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:77
 ShowOverlayGlow = <function> defined @Interface\AddOns\NDui\Libs\LibButtonGlow.lua:181
 Mover = <function> defined @Interface\AddOns\NDui\Core\Mover.lua:38
 RestoreMF = <function> defined @Interface\AddOns\NDui\Core\Mover.lua:26
 CreateMF = <function> defined @Interface\AddOns\NDui\Core\Mover.lua:8
 ReskinTab = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:875
 ReskinRadio = <function> defined @Interface\AddOns\NDui\Core\Functions.lua:1139
 CreateSlider = <function> defined @Interface\AddOns\NDui

**Error 2:**
Message: NDui_Plus: Chat Module error
Interface\AddOns\NDui_Plus\Modules\Chat\ChatHide.lua:237: UIParent:SetParent(): Would create a loop parenting to NDui_PlusChatBG
Time: Fri Sep  9 20:29:17 2022
Count: 1
Stack: NDui_Plus: Chat Module error
Interface\AddOns\NDui_Plus\Modules\Chat\ChatHide.lua:237: UIParent:SetParent(): Would create a loop parenting to NDui_PlusChatBG

Locals: <none>

**Comment by siweia** [comment]
Show be fixed in today's release.
