### ISSUE TITLE
背包排序会造成反序

### ISSUE THREAD

**Issue by cube1in** [siweia/NDui#183]
### 情形描述

我在使用NDui的默认背包整合没有任何问题。

但当我关闭默认的背包整合，改用Combuctor插件时，背包的排序将会变为反序（关闭NDui后此问题消失，所以初步判定是NDui造成的）。

#### 具体如图

![image](https://user-images.githubusercontent.com/58240137/189595389-15c184cc-a746-4fe0-95f9-7f8199b2f2aa.png)

![image](https://user-images.githubusercontent.com/58240137/189595576-3f98f585-da97-4603-94c2-13dabaab158b.png)

#### 这不是一个严重的BUG，也许也不能称为BUG，自行更改一下Combuctor的配置也可以修复。

但我还是将此问题报告给开发者您

**Comment by siweia** [comment]
你自己看下ndui背包设置里你设置的正反序，这个会影响其他插件

**Comment by cube1in** [comment]
我并没有开启ndui的背包整合。

我再次尝试更改“背包整理模式”发现无论选择哪个，都没有反应

![image](https://user-images.githubusercontent.com/58240137/189664368-6e984da5-6935-4a32-8f3e-a384df61eb6f.png)

**Comment by cube1in** [comment]
我也尝试了开启ndui的背包整合后，然后更改“背包整理样式”，然后关闭ndui的背包整合。但还是没有变化

**Comment by cube1in** [comment]
@siweia 您好，我按照您的方法修改了代码，发现背包的排序已经恢复正常，但银行的这一问题还是没有解决。

我后续将combuctor更换为了bagnon，发现也是这一问题。

考虑到是否ndui内部排序是反着来的，所以导致在使用其他插件时会造成此问题（别的插件都不调用自己的吗？😥）

**Comment by siweia** [comment]
就用自带背包不就好了，为什么还要装个别的

**Comment by cube1in** [comment]
@siweia 我本来用着ndui的背包的，但由于它是透明度太高了，导致我看不太清物品栏

**Comment by siweia** [comment]
删除bags/sortbags文件
