### ISSUE TITLE
换装毁导致属性面板错乱并报lua错误

### ISSUE THREAD

**Issue by mruru** [siweia/NDui#184]
1.当更换任意一件装备时，属性面板收缩，导致排版混乱
2.同事右下角提示一个错误类似“addons\ndui\libs\libhealcomm-4.0.lua:817......

**Comment by siweia** [comment]
请学会如何正确的反馈问题

**Comment by mruru** [comment]
不知道提交一些问题还要学习什么反馈方式。
就算我没说话把
请关闭这个issues

**Comment by siweia** [comment]
版本号不发，报错不发，截图也没有。鬼知道你在说什么？
你还是去NGA反馈，按照模板好了。https://nga.178.com/read.php?tid=18321155

看看隔壁别人的反馈，我都没跟他说过话，人家都讲的详详细细的。
https://github.com/siweia/NDui/issues/185
