### ISSUE TITLE
取消勾选“美化暴雪自带插件”后，出现画面错误

### ISSUE THREAD

**Issue by cube1in** [siweia/NDui#185]
我下载您的代码后，发现还是有些许问题出现

具体如下：

![image](https://user-images.githubusercontent.com/58240137/189692026-b06fa7ad-699e-45da-aa0d-eeadeef083e5.png)

可能造成的原因：

1. 滚动条显示与否可能需要加入判断

2. 滚动条的样式貌似没有对齐，出现有偏差

3. **底边**原版中三个按钮的位置的样式貌似还保留着

4.  **详情框右侧**的滚动条样式貌似还保留着

_Originally posted by @cube1in in https://github.com/siweia/NDui/issues/182#issuecomment-1243890493_

**Comment by cube1in** [comment]
我在想，当用户取消勾选“美化暴雪自带插件”时，将“拓展专业及附魔界面”也一起禁用

![image](https://user-images.githubusercontent.com/58240137/189693814-6cb47480-e11a-4dfd-a397-0657e555239e.png)

此时，如果禁用，则完美解决

![image](https://user-images.githubusercontent.com/58240137/189693968-441ca9f7-573b-4ae9-a3b4-560a20604694.png)

**Comment by siweia** [comment]
不考虑，自己可以自行关闭。

**Comment by siweia** [comment]
材质不是一块块的，要拓展这个是隐藏不了的

**Comment by cube1in** [comment]
> 材质不是一块块的，要拓展这个是隐藏不了的

所以滚动条样式的问题也无法解决了吗

**Comment by cube1in** [comment]
@siweia

**Comment by siweia** [comment]
这些都是材质的一部分，并不是你以为的滚动条。该显示的时候都会显示的

**Comment by cube1in** [comment]
谢谢您的解释，我明白您的意思

**Comment by siweia** [comment]
![{7CBAR@5K@IWW 1GLIN0E7D](https://user-images.githubusercontent.com/1502922/189836605-05b451a7-0128-41ef-ade2-7deb11c98e37.png)
加了3个色块，挡住你说的地方，看着好像稍微好一点

**Comment by cube1in** [comment]
@siweia 不止稍微好一些，简直完美。非常感谢
