### ISSUE TITLE
NDUI WLK 战场面板无法显示[NDUI版本 3.31 ]

### ISSUE THREAD

**Issue by crazybear** [siweia/NDui#187]
NDUI版本 3.31 

在达纳苏斯排战场，美化暴雪自带插件
第一次点击我想去战场面板可以显示，关闭后第二次就无法显示（可以切换战场PVP tab来显示出来）
并且选择战场时字体颜色是黑色的

NDUI配置
TkR1aVNldHRpbmdzOjMuMy4xOuWFg+awlOajruaelzpST0dVRTtOYW1lcGxhdGU6Q3VzdG9tVW5pdHM7TmFtZXBsYXRlOkF1cmFTaXplOjIyO05hbWVwbGF0ZTpTZWN1cmVDb2xvcjpyOjE6ZzowOmI6MTtOYW1lcGxhdGU6VGFyZ2V0Q29sb3I6cjowOmc6MC42OmI6MTtOYW1lcGxhdGU6SGVhbHRoVGV4dFNpemU6MTI7TmFtZXBsYXRlOkZvY3VzQ29sb3I6cjoxOmc6MC44OmI6MDtOYW1lcGxhdGU6Q3VzdG9tQ29sb3I6cjowOmc6MC44OmI6MC4zO05hbWVwbGF0ZTpQbGF0ZUhlaWdodDoxMDtOYW1lcGxhdGU6U2hvd1BsYXllclBsYXRlOnRydWU7TmFtZXBsYXRlOlBsYXRlV2lkdGg6MTM1O05hbWVwbGF0ZTpJbnNlY3VyZUNvbG9yOnI6MTpnOjA6YjowO05hbWVwbGF0ZTpOYW1lVGV4dFNpemU6MTI7TmFtZXBsYXRlOlBQUG93ZXJUZXh0OnRydWU7TmFtZXBsYXRlOlRyYW5zQ29sb3I6cjoxOmc6MC44OmI6MDtOYW1lcGxhdGU6VGFua01vZGU6dHJ1ZTtOYW1lcGxhdGU6UG93ZXJVbml0cztOYW1lcGxhdGU6RG90U3BlbGxzO05hbWVwbGF0ZTpEb3RDb2xvcjpyOjE6ZzowLjU6YjowLjI7TmFtZXBsYXRlOk9mZlRhbmtDb2xvcjpyOjAuMjpnOjAuNzpiOjAuNTtNaXNjOlN0YXRFeHBhbmQ6ZmFsc2U7TWlzYzpFeHBsb3NpdmVDYWNoZTpFTVBUWVRBQkxFO1R1dG9yaWFsOkNvbXBsZXRlOnRydWU7QmFnczpTcGVjaWFsQmFnc0NvbG9yOnRydWU7QmFnczpDdXN0b21OYW1lcztCYWdzOkN1c3RvbUl0ZW1zOjE5NDEwMToxOjQwNDgzOjE6Njk0ODoxO0F1cmFzOlRvdGVtczpmYWxzZTtBdXJhczpEZWJ1ZmZTaXplOjM0O01vdmVyOlF1ZXN0VHJhY2tlcjpUT1BSSUdIVDpVSVBhcmVudDpUT1BSSUdIVDotNTU6LTI4MDtTa2luczpGb250T3V0bGluZTpmYWxzZTtTa2luczpSZXNldFJlY291bnQ6ZmFsc2U7U2tpbnM6RmxhdE1vZGU6dHJ1ZTtBY3Rpb25iYXI6QmluZFR5cGU6MjtBY3Rpb25iYXI6TWFjcm86ZmFsc2U7Q2hhdDpDaGF0V2lkdGg6NDYzO1VGczpTaW1wbGVNb2RlOnRydWU7VUZzOkhlYWx0aEZyZXF1ZW5jeTowLjI1O1VGczpDYXN0aW5nQ29sb3I6cjowLjM6ZzowLjc6YjoxO1VGczpQbGF5ZXJEZWJ1ZmZUeXBlOjI7QUNDT1VOVDpEaXNhYmxlSW5mb2JhcnM6ZmFsc2U7QUNDT1VOVDpDb3JuZXJTcGVsbHM6Uk9HVUU7QUNDT1VOVDpJZ25vcmVkQnV0dG9uczo7QUNDT1VOVDpDaGF0RmlsdGVyTGlzdDrliqjovaYgM0cg6Iiq56m6O0FDQ09VTlQ6UHJvZmlsZUluZGV4OuWFg+awlOajruaely3mm7zlpJrln7rlsJQ6MTroi4/msqvoi5It5pu85aSa5Z+65bCUOjE66IuP5LiD6IuSLeabvOWkmuWfuuWwlDoyO0FDQ09VTlQ6Q29udGFjdExpc3Q65YWD5rCU5qOu5p6XLeabvOWkmuWfuuWwlDoxOjE6MTroi4/kuIPoi5It5pu85aSa5Z+65bCUOjE6MToxOuWltuayueWGt+iQgy3mm7zlpJrln7rlsJQ6MToxOjE7QUNDT1VOVDpEQk1SZXF1ZXN0OmZhbHNlO0FDQ09VTlQ6Q3VzdG9tVGV4OjtBQ0NPVU5UOkF1dG9TZWxsOnRydWU7QUNDT1VOVDpDaGF0RmlsdGVyV2hpdGVMaXN0OjtBQ0NPVU5UOkNsaWNrU2V0czpST0dVRTtBQ0NPVU5UOlJhaWRCdWZmc1doaXRlO0FDQ09VTlQ6U2thZGFSZXF1ZXN0OnRydWU7QUNDT1VOVDpMb2NrVUlTY2FsZTpmYWxzZTtBQ0NPVU5UOlNob3dTbG90czpmYWxzZTtBQ0NPVU5UOkd1aWxkU29ydE9yZGVyOnRydWU7QUNDT1VOVDpWZXJzaW9uQ2hlY2s6dHJ1ZTtBQ0NPVU5UOkF1dG9CdWJibGVzOmZhbHNlO0FDQ09VTlQ6QXV0b1JlY3ljbGU6ZmFsc2U7QUNDT1VOVDpSYWlkRGVidWZmc0JsYWNrO0FDQ09VTlQ6TmFtZXBsYXRlQmxhY2s7QUNDT1VOVDpOYW1lcGxhdGVXaGl0ZTtBQ0NPVU5UOlByb2ZpbGVOYW1lczoxOuinkuiJsumFjee9rjoyOuWFseS6q+mFjee9rjE6MzpESzo0OuWFseS6q+mFjee9rjM6NTrlhbHkuqvphY3nva40OjY65YWx5Lqr6YWN572uNTtBQ0NPVU5UOkJXUmVxdWVzdDp0cnVl

**Comment by siweia** [comment]
下载github的版本，这个问题应该修复过了

**Comment by crazybear** [comment]
> 下载github的版本，这个问题应该修复过了

ok

**Comment by crazybear** [comment]
还是有一些小问题，排战场的时候简介文字还是黑色的。。。在黑色半透明面板上看不清呢

**Comment by siweia** [comment]
不要关闭描边，应该就不会黑色
