### ISSUE TITLE
wlk 合剂/药剂

### ISSUE THREAD

**Issue by nanjuekaien1** [siweia/NDui#190]
------合剂------
53758 【石血合剂】生命值上限提高1300点
54212【纯净魔精合剂】每5秒法力值回复提高45点
53760【无尽怒气合剂】攻击强度提高180点
53755【冰霜巨龙合剂】法术强度提高125点
------药剂------
----战斗--
28497【极效敏捷】使你的敏捷提高45点
53746【怒火药剂】攻击强度提高90点
33721【法能药剂】法术强度提高58点
53748【强效力量】使你的力量值提高50点
53749【专家药剂】所有属性提高20点
60340【精准】使你的命中等级提高45
60341【致命打击】使你的爆击等级提高45
60345【护甲穿透】使你的护甲穿透等级提高45
60346【闪电之速】使你的急速等级提高45
----守护----
60347【强效思维】使你的智力提高45点
60343【强效防御】使你的防御等级提高45
53764【强效法力回复】每5秒恢复30点法力值
53763【防护】护甲值提高800点
53751【极效坚韧药剂】生命值上限提高350点，每5秒恢复20点生命值
53747【精神药水】精神值提高50点

**Comment by siweia** [comment]
好像用不上，怀旧服我压根就没做buff检查的功能

**Comment by nanjuekaien1** [comment]
那就关闭吧。
