### ISSUE TITLE
Weak Aura Conflict

### ISSUE THREAD

**Issue by ProfessorMc** [siweia/NDui#196]
Weak Aura Conflict on latest update.  UI fails to finish loading after this.

Date: 2022-10-26 00:01:13
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\NDui\Modules\Skins\AddOns\WeakAuras.lua line 68:
   attempt to index local 'regionTypes' (a nil value)
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=[C]"]: ?
   [string "@NDui\Modules\Skins\AddOns\WeakAuras.lua"]:68: func()
   [string "@NDui\Modules\Skins\Skins.lua"]:23: LoadSkins()
   [string "@NDui\Modules\Skins\Skins.lua"]:46: LoadAddOnSkins()
   [string "@NDui\Modules\Skins\Skins.lua"]:77: OnLogin()
   [string "@NDui\Init.lua"]:117: func()
   [string "@NDui\Init.lua"]:23:
      NDui\Init.lua:18
Locals:
errMsg = "...rface\AddOns\NDui\Modules\Skins\AddOns\WeakAuras.lua:68: attempt to index local 'regionTypes' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.7.2-3-g004ec6b
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  ATTClassic, v1.1.9
  Attune, v308
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  Auctionator, v10.0.0
  BagBrother, v
  Bagnon, v10.0.3
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  DBMCore, v494a4d8
  DBMStatusBarTimers, v494a4d8
  DBMVPVEM, v47b3faf
  Details, v#Details.DF.SL.Wrath.10144.146-12-gfabfe11
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  ExRT, v4680
  ExtendedCharacterStats, v3.0.7
  FaceMelterClassic, v0.8.0
  HealBot, v3.4.0.14
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  Informant, v3.4.6814 (SwimmingSeadragon)
  MRT, v4680
  NDui, v3.5.0
  NovaInstanceTracker, v1.37
  NovaWorldBuffs, v2.39
  OmniCC, v9.2.1
  Pawn, v2.7.5
  Plater, vPlater-v537.1-Wrath
  Questie, v7.4.2
  RareScanner, v3.4.0.3
  RCLootCouncilClassic, v0.16.1
  Scrap, v10.0.2
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TacoTip, v0.2.8
  ThreatClassic2, v2.45
  TomTom, vv3.2.0-release
  TradeSkillMaster, vv4.11.58
  TradeSkillMasterAppHelper, vv4.0.23
  WeakAuras, v5.0.1
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=6da)

**Comment by ProfessorMc** [comment]
Following up, downgrade of weak aura version to previous, corrects the issue, so it looks like WA broke your lib.

**Comment by siweia** [comment]
Show be fixed in recent commit.
