### ISSUE TITLE
Rendering Issue - New Actionbars

### ISSUE THREAD

**Issue by RodiakWolfshain** [siweia/NDui#199]
Hey Siweia,

if you start a fresh character, Blizzard shows only one Actionbar. If you add more of them to the UI, Bar 2 + 3 are placed somewhere strange. 
"MoveUI" shows the correct placement, but the bars itself are renderd somewhere else. 

This is something I was able to see also, if you, for example, dont have a pet active and summon it. In this case, the petbar is placed somewhere else, too. 

A simple /reload fix the issue, 

Version: 6.29.5 (SL)

See Screenshots attached
![WoWScrnShot_102722_153733](https://user-images.githubusercontent.com/65841447/198301358-7e8cd684-7227-485e-b12e-9b9408e08217.jpg)
![WoWScrnShot_102722_153747](https://user-images.githubusercontent.com/65841447/198301365-4645af45-d446-4c6f-8c34-4395dcb1b738.jpg)
![WoWScrnShot_102722_154004](https://user-images.githubusercontent.com/65841447/198301367-6b88e04c-d1e1-4f93-aa46-9188f6ff15dd.jpg)

**Comment by RodiakWolfshain** [comment]
Ahh... Its fine. I mean, I love your addon. So I will put everything I found here. Nice thing is, that I can give you feedback after a new version comes out, and I was able to test it. Like the vehiclebar ;)
And Bugs are normal on such a big UI Overhaul, Blizzard made.

**Comment by D2junkie** [comment]
So I'm having a similar issue with the pet actionbar, when I unlock NDui the frame shows where I want it to be but the bar itself is actually right under the Player UF frame.
![WoWScrnShot_102722_130121](https://user-images.githubusercontent.com/38031134/198353460-6ccce267-cbc1-45b7-bffe-8b96e1cc7b46.jpg)
![WoWScrnShot_102722_130126](https://user-images.githubusercontent.com/38031134/198353466-a21fd7f9-4871-4de9-86c5-afc1de39705b.jpg)

**Comment by siweia** [comment]
I meant disable it, until I solve the issue.

**Comment by siweia** [comment]
Should be fixed with commits lately.
