### ISSUE TITLE
Screenfreeze

### ISSUE THREAD

**Issue by Sephiroth105** [siweia/NDui#20]
Hi,
my problem is that every time if I leave a Combat, it happens that my fps are dropping down for a 0,5 sec. Can you help me by the way? Ive disabled the "SimpleCombatText" but it doesnt help me further. I really like your UI and I use it all a Long time and I didnt had this problem earlier.
![inkedwowscrnshot_110418_183138_li](https://user-images.githubusercontent.com/36588469/47967844-40993780-e062-11e8-9639-e242654372f5.jpg)

**Comment by siweia** [comment]
I can't replicate the problem. Are there any other addons in your package, rather than mine?
Everything seems to be OK on my warlock account.

**Comment by Sephiroth105** [comment]
Yes they are but Ive tried it without other addons and the problem is still there. It doesnt matter which character Im using. Ist the same problem by everyone. After the Combat the screen freezes for a half second.

**Comment by Sephiroth105** [comment]
https://youtu.be/5bgkSflizLE
This link Shows you a Video where you can see after the combat my problem

**Comment by siweia** [comment]
Ok, I would go and check again after work. It might be something in different locales.

**Comment by Sephiroth105** [comment]
Thank you very much^^

**Comment by Sephiroth105** [comment]
Oh OK. Then should it be a problem in my Computer :(. Thank you so much for looking after it. I still use this UI because i like it so much 👍 👍 👍 🥇

**Comment by siweia** [comment]
I played all night, and now finally realise whats going on here.
Try the new version, it should be fixed now.
