### ISSUE TITLE
Ndui has been disabled because the feature is only open to Blizzard's ui

### ISSUE THREAD

**Issue by vtwr** [siweia/NDui#201]
![image](https://user-images.githubusercontent.com/35043739/198618580-f07c4dd0-ed46-4f0c-a3f6-881b0a8f850c.png)
I recorded a video, but found that github can only upload videos under 10mb..

I can't use my keyboard to cast spells right now, when I use the keyboard it says
  ‘Ndui has been disabled because the feature is only open to Blizzard’s ui’ .     Except for the '1' key, above the 'Q'

I can only cast spells with mouse clicks unless I/RL. But as long as I switch any map or any scene, the skills cannot be released through the shortcut keys.

**Comment by vtwr** [comment]
https://user-images.githubusercontent.com/35043739/198623371-f99244a6-5c09-4a11-a98e-d49d38f376d7.mp4

I was afraid that my expression was not clear, so I recorded a short video below 10mb.

**Comment by nanjuekaien1** [comment]
这是暴雪的BUG，等暴雪修复吧。
进副本、过图、读条后快捷键都会失效，需要/rl 才可以再次使用快捷键。
你可以去奥利波斯试下1楼传送2楼或者2楼传送1楼，你的快捷键也能失效。

**Comment by vtwr** [comment]
> 这是副本雪的UG，去修复。进副本、读后 暴2等暴楼 过失杀戮，需要才可以使用白雪皑皑的图吧/BU1。楼传送1楼，你的能量也能失效。

我用elvui的朋友就不会啊，但是我们团就我用ndui，很难受

**Comment by vtwr** [comment]
> 这是暴雪的BUG，等暴雪修复吧。 进副本、过图、读条后快捷键都会失效，需要/rl 才可以再次使用快捷键。 你可以去奥利波斯试下1楼传送2楼或者2楼传送1楼，你的快捷键也能失效。

我用elvui的朋友就不会啊，但是我们团就我用ndui，很难受

**Comment by siweia** [comment]
版本呢？

**Comment by nanjuekaien1** [comment]
刚才在NGA@我啥了。。。。楼层被吃到现在都看不到。。

**Comment by siweia** [comment]
> 刚才在NGA@我啥了。。。。楼层被吃到现在都看不到。。

ndui从来没有美化过wa的控制台，这个部分都是nduiplus在负责

**Comment by vtwr** [comment]
> 版本呢？

早上确认了一下，是6.29.6，昨天记错了抱歉

**Comment by nanjuekaien1** [comment]
还有预建队伍双击申请也需要修复下。。。现在双击申请也失效

**Comment by vtwr** [comment]
此问题已在今天更新的6.29.9版本中得到解决
