### ISSUE TITLE
Action Bars not working for me

### ISSUE THREAD

**Issue by Grumpyrowley** [siweia/NDui#203]
![WoWScrnShot_102922_144533](https://user-images.githubusercontent.com/116960320/198836144-81536ae0-b6e7-4a8d-b740-5ce8bfa84fc4.jpg)

For some reason I am unable to get the action bars working,
I have tried a fresh install and deleting my cache and wtf folders

In the DNui Console the Enable Actionbar is unchecked, when I click it and reload it remains unchecked once the ui has reloaded.

If I CTRL and click one of the buttons to set the bars to my preference I get the following error

Message: ...e/AddOns/NDui/Modules/ActionBar/Bars/StylePreset.lua:116: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Sat Oct 29 15:17:57 2022
Count: 1
Stack: ...e/AddOns/NDui/Modules/ActionBar/Bars/StylePreset.lua:116: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Interface/AddOns/NDui/Modules/ActionBar/Bars/StylePreset.lua"]:116: in function `ExportActionbarStyle'
[string "@Interface/AddOns/NDui/Core/ExtraGUI.lua"]:1961: in function `OnShow'
[string "@Interface/FrameXML/StaticPopup.lua"]:5175: in function `StaticPopup_OnShow'
[string "*StaticPopup.xml:244_OnShow"]:1: in function <[string "*StaticPopup.xml:244_OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/StaticPopup.lua"]:4971: in function <Interface/FrameXML/StaticPopup.lua:4497>
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@Interface/AddOns/NDui/Core/ExtraGUI.lua"]:2003: in function <Interface/AddOns/NDui/Core/ExtraGUI.lua:2001>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Thanks in advance
Peter

**Comment by siweia** [comment]
it is currently disabled on purpose.
