### ISSUE TITLE
Bag Favorites using wrong name/group

### ISSUE THREAD

**Issue by zouLIFEE** [siweia/NDui#204]
Version: 6.29.6

Hello siweia,

favorite mode in bag has following problem:

First favorite group uses name of second.
Second favorite group uses name of third.
Third uses name of fourth.
and so on
The 5th group uses "Preferences 6" as Name.

I've recorded a video of it and uploaded it to YT: https://youtu.be/q7tpDKGmEVI
Currently uploading, if video doesnt load check back later 👍 

I can only image 2 things happening here:

Items get put into wrong group when assigning
or wrong names are assigned to each group.

Thank you for your great work. Ive been using your UI since i returned to WoW in 9.0.5 - and its great.

**Comment by zouLIFEE** [comment]
Updated to 6.29.9 - problem described above still persist

**Comment by siweia** [comment]
Should be fixed now.

**Comment by zouLIFEE** [comment]
Updated to master after commit b16c9c1da77c08a793e8b111aa904f695bff3a6e

Problem in bag is now fixed. Issue now switched to Bank.

Preference 1 uses Name of Preference 0
Preference 2 uses Name of Preference 1
Preference 3 uses Name of Preference 2

and so on

Thank you for putting in effort into this

**Comment by siweia** [comment]
Try now, should be cool by now.

**Comment by zouLIFEE** [comment]
All fixed now, thank you for your effort siweia 👍
