### ISSUE TITLE
On classic era UI problems

### ISSUE THREAD

**Issue by ibosher** [siweia/NDui#207]
Hello after some patchs on classic era addon stopped working. Pls do smth its the best one.
9/13/2022
NDui-1.38.0-classic.zip
Release
1.14.3

![image](https://user-images.githubusercontent.com/63596329/199502739-ce4fe1de-ae39-431b-8035-e4dea01f02ca.png)

**Comment by siweia** [comment]
Do you have addon WA installed?

**Comment by ibosher** [comment]
Yes. Today update fixed the issue. Great thanks
