### ISSUE TITLE
Getting some lua errors after the most recent update.

### ISSUE THREAD

**Issue by D2junkie** [siweia/NDui#213]
![image](https://user-images.githubusercontent.com/38031134/201411213-3128587b-c054-4f1e-b814-8b376190b866.png)
![image](https://user-images.githubusercontent.com/38031134/201411243-8a0f2441-9441-4260-aebd-26a8cd163718.png)

**Comment by siweia** [comment]
My motherboard was down lately, havent got time to test the bars yet

**Comment by Gizmo855** [comment]
Guten morgen habe den Fehler auch.

**Comment by Gizmo855** [comment]
Huhu wann können sie den Fehler beheben möchte es wieder Installieren.

MFG Gizmo

**Comment by gaohan250** [comment]
hi, i recently got the same error, i think the Ndui is having a conflic with the wow original UI.  
heres the error :  

28x ...AddOns/NDui/Modules/ActionBar/Bars/Hide_blizzart.lua:63: attempt to call global 'BackpackTokenFrame_Update' (a nil value)
[string "@Interface/AddOns/NDui/Modules/ActionBar/Bars/Hide_blizzart.lua"]:63: in function `func'
[string "@Interface/AddOns/NDui/Init.lua"]:23: in function <Interface/AddOns/NDui/Init.lua:18>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'BackpackTokenFrame_Update' (a nil value)"


hope it helps...

**Comment by siweia** [comment]
Dont you never ever update your addon?

> hi, i recently got the same error, i think the Ndui is having a conflic with the wow original UI. heres the error :
> 
> 28x ...AddOns/NDui/Modules/ActionBar/Bars/Hide_blizzart.lua:63: attempt to call global 'BackpackTokenFrame_Update' (a nil value) [string "@Interface/AddOns/NDui/Modules/ActionBar/Bars/Hide_blizzart.lua"]:63: in function `func' [string "@Interface/AddOns/NDui/Init.lua"]:23: in function <Interface/AddOns/NDui/Init.lua:18>
> 
> Locals: (*temporary) = nil (*temporary) = "attempt to call global 'BackpackTokenFrame_Update' (a nil value)"
> 
> hope it helps...

**Comment by Gizmo855** [comment]
Guten morgen bekomme trotzdem die Fehler Meldung auch bei 6.30.3 was kann ich machen Bitte um Hilfe.

**Comment by siweia** [comment]
> Guten morgen bekomme trotzdem die Fehler Meldung auch bei 6.30.3 was kann ich machen Bitte um Hilfe.

Download addon NoTaint2

**Comment by gaohan250** [comment]
> 

uhm... i did and its newest version( 6.30.3) . downloaded on curseforge.  still having the same problems.  =(

**Comment by siweia** [comment]
> > 
> 
> uhm... i did and its newest version( 6.30.3) . downloaded on curseforge. still having the same problems. =(

If you are new to this game, please download addon thru curseforge client, instead of web page.
The error you posted earlier only proves that you don't even know how to place your addon file.

**Comment by Gizmo855** [comment]
Guten Morgen wollte mal Fragen ob man bei dem Gold ein Komma Setzten kann also 1,2 Millionen?

MFG Gizmo

**Comment by siweia** [comment]
Should be fixed since 6.30.5.
