### ISSUE TITLE
Wrath fps problem

### ISSUE THREAD

**Issue by Irsont** [siweia/NDui#216]
Hi, I was in the raid 25, and i have drop fps(jump fps /freezing in fight), i disable all addon except Ndui, but fps drop again, after disable UI fps is fine.
it happens only in Raid 25 or 20+player in party!! small bg/dungers/raid 10 and other its fine!
i tried elvui/kkthnx , elvui dont drop fps but kkthnx have the same problem, are similar, maybe you know what the problem

**Comment by siweia** [comment]
No idea. I don't play classic at all, no way to test it atm.
