### ISSUE TITLE
CR with middle mouse click not working

### ISSUE THREAD

**Issue by Zeddicus40** [siweia/NDui#219]
Hi !

I've updated NDui with the lastest version  and ran some dungeons.

The option to CR someone with the middle click on the party frame is not working with my warlock soulstone (it's casting the soulstone on me), I have not tested with another CR class. I've not changed any setting concerning this. It was working in the 9.2 version of the game.

**Comment by siweia** [comment]
Do you have Clique installed?

**Comment by Zeddicus40** [comment]
Clique is not installed

**Comment by Zeddicus40** [comment]
It's working on target that is alive but not on a dead one

**Comment by siweia** [comment]
I believe should be the issue in blizzard settings. I have tested two characters, one works, one doesn't.

**Comment by Zeddicus40** [comment]
I'll give it a try, but it's weird as I've added no new addon only updated them and not changed any settings. Maybe something with new blizzard UI entering in conflict on my side. I'll investigate.

**Comment by Zeddicus40** [comment]
After a few tests, it seems to conflict with AdvancedInterfaceOptions addon. I'll try to investigate into this side

**Comment by siweia** [comment]
search for 'keydown'

**Comment by Zeddicus40** [comment]
In the addon or into blizzard settings ?

**Comment by siweia** [comment]
In your AIO addon. Enable that cvar.

**Comment by Zeddicus40** [comment]
The setting was already on, i've set it to 0 and back to 1 it worked. I've reloaded to see if it works after a reload i'll tell you this once the cooldown is gone ^^

**Comment by Zeddicus40** [comment]
It worked after setting the setting on 0 then set it back to 1 as it was set already. After a reload and not touching anything it still worked.

It's fixed so ! It seems that the game update bugged the cvar by itself and needed to be refreshed.
