### ISSUE TITLE
Using GSE ERROR

### ISSUE THREAD

**Issue by yypboy** [siweia/NDui#220]
When you install GSE, when you enter the copy, you will be prompted that ndui is not a plug-in certified by Blizzard. At this time, you must use reloadui every time to use GSE macros normally.

**Comment by siweia** [comment]
Works fine on mine.

**Comment by yypboy** [comment]
……ok，我就这样用吧，每次reload也不是很麻烦



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 22, 2022 16:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siweia/NDui] Using GSE ERROR (Issue #220)




 
Works fine on mine.
