### ISSUE TITLE
Flyout spells on custom bar

### ISSUE THREAD

**Issue by Zeddicus40** [siweia/NDui#221]
Using a Flyout spell (like summon demon, portals etc) in the Custom Bar  cause the following LUA error

Using them onto any normal bar works great

Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)

Count: 1

Call Stack:
[string "=[C]"]: in function `GetSpellFlyoutDirection'
[string "@Interface/FrameXML/SpellFlyout.lua"]:240: in function `Toggle'
[string "@Interface/FrameXML/SecureTemplates.lua"]:361: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:1149: in function <Interface/FrameXML/ActionButton.lua:1119>
[string "=[C]"]: ?

**Comment by siweia** [comment]
dont use flyout button on custombar and mainbar.

**Comment by Zeddicus40** [comment]
I was using the custom bar for all my teleports. I'll wait for a fix then :)
