### ISSUE TITLE
Latest update breaks Bagnon

### ISSUE THREAD

**Issue by ProfessorMc** [siweia/NDui#225]
This latest issue breaks Bagnon.  Downgrading to 3.4.3-NDUI removes issue.

Date: 2022-11-23 20:25:07
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua line 188:
   attempt to call field 'GetBagSlotFlag' (a nil value)
Debug:
   [string "@RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: origErrorHandler()
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:769:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:725
   [string "=[C]"]: GetBagSlotFlag()
   [string "@Bagnon\common\Wildpants\classes\bag.lua"]:188: Update()
   [string "@Bagnon\common\Wildpants\classes\bag.lua"]:124: RegisterEvents()
   [string "@Bagnon\common\Wildpants\classes\bag.lua"]:73:
      ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:18
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\classes\bagGroup.lua"]:17:
      ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11
   [string "=(tail call)"]: ?
   [string "@Bagnon\addons\main\frame.lua"]:285: CreateBagGroup()
   [string "@Bagnon\addons\main\frame.lua"]:265: PlaceBagGroup()
   [string "@Bagnon\addons\main\frame.lua"]:91: Layout()
   [string "@Bagnon\addons\main\frame.lua"]:66: Update()
   [string "@Bagnon\addons\main\frame.lua"]:56: RegisterSignals()
   [string "@Bagnon\common\Wildpants\classes\frame.lua"]:19:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\classes\inventory.lua"]:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [string "=[C]"]: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:85: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:82: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:611

AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.8.4
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  ATTClassic, v1.2.4
  Attune, v308
  AucAdvanced, v3.4.6844 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  Auctionator, v10.0.13
  BagBrother, v
  Bagnon, v10.0.3
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  Clique, vv3.4.10-release
  DBMCore, v5b00279
  DBMStatusBarTimers, v5b00279
  DBMVPVEM, v0dab85c
  Decursive, v2.7.8.11
  Details, v#Details.DF.Wrath.10259.146-15-g1f60774
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6849 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  ExRT, v4680
  ExtendedCharacterStats, v3.0.7
  FaceMelterClassic, v0.8.0
  FaceMelterWotlk, v0.0.1-beta
  Gargul, v4.12.11
  Grid2, v2.0.67
  Grid2LDB, v2.0.67
  Grid2RaidDebuffs, v2.0.67
  HealBot, v3.4.0.23
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  Informant, v3.4.6850 (SwimmingSeadragon)
  InstanceAchievementTracker, v4.5.0
  MRT, v4680
  NDui, v3.5.6
  NovaInstanceTracker, v1.37
  NovaWorldBuffs, v2.40
  NugComboBar, v10.0.2
  OmniCC, v10.0.1
  Pawn, v2.7.12
  Plater, vPlater-v538-Wrath
  ProfessionCooldown, v1.18
  Questie, v7.4.5
  RareScanner, v3.4.0.3
  RCLootCouncilClassic, v0.16.1
  RXPGuides, vv4.4.3
  Scrap, v10.0.3
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TacoTip, v0.3.3
  ThreatClassic2, v2.45
  TidyPlatesThreatPlates, v11.1.1
  TomTom, v3.3.5-release
  TradeSkillMaster, vv4.11.71
  TradeSkillMasterAppHelper, vv4.0.23
  WeakAuras, v5.2.0
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=800)

**Comment by siweia** [comment]
Should have been fixed in ae6f41715d56b6814bb32056d717c2503c54f375
