### ISSUE TITLE
dublicate totem icon in totem bar and sorting

### ISSUE THREAD

**Issue by Irsont** [siweia/NDui#228]
`wrath`
### 1. Slot 4 nature resist totem dublicate (58749, 25574) 6 and 4 skill lvl
![image](https://user-images.githubusercontent.com/99548130/204156278-0f2cb0d3-1a07-4717-9305-7421efc28903.png)
### 2. invalid sorting in totem bar
![image](https://user-images.githubusercontent.com/99548130/204156536-5d92e680-3ffe-4224-ab2f-e54401f4998b.png)

**Comment by siweia** [comment]
Check the issue when all addons disabled, include ndui.

**Comment by Irsont** [comment]
only ndui enable

**Comment by siweia** [comment]
I meant disable all addons.

**Comment by Irsont** [comment]
i disable all addon, and enable only ndui

![image](https://user-images.githubusercontent.com/99548130/204157666-5ffba665-0142-477a-aa20-f6e297ec51b6.png)

**Comment by Irsont** [comment]
same
![image](https://user-images.githubusercontent.com/99548130/204157766-248bf06b-4eb1-4aa7-bdfc-2155f51f97b9.png)

**Comment by Irsont** [comment]
sorting can be fixed?
elvui good
![image](https://user-images.githubusercontent.com/99548130/204158096-5ad1cb89-d6de-4d70-a67b-091396bf6bcc.png)

**Comment by siweia** [comment]
No. If you want totem to be removal but right click, you have to follow its order.
