### ISSUE TITLE
No sound from !BaudErrorFrame

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [siweia/NDui#23]
Hi, siweia

BaudErrorFrame When I looked at the Lua file, I get a sound when an error is output.

However, in the game there is no sound even if the Lua Error is output.

I even switched from "EnableSound=false to true"

Can I find out why there is no sound?

**Comment by siweia** [comment]
The config part has been removed for a long time.
I might have a tweat on it somehow.
