### ISSUE TITLE
some nameplate widget bars are too big and showing classification star

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#231]
![image](https://user-images.githubusercontent.com/40672673/209180674-3368a231-ddde-4000-8ed0-a43bc2772268.png)

So some of these bars are so big and this is indeed how blizzard has them set as well. Is there anything we can do here to adjust for this?

**Comment by siweia** [comment]
You can remove its setscale code in nameplate.lua, but some widgets might become too small to tell.
