### ISSUE TITLE
ndui有没有类似的loot情况查看功能

### ISSUE THREAD

**Issue by hlykl680** [siweia/NDui#232]
elvui有自带的loot需求情况统计 ndui有吗 是我没有找到吗
![09fc699ef9f4bbbf114873edb9c1667](https://user-images.githubusercontent.com/31556657/209561252-b2c4a8dc-4d5a-49e4-ad92-4fe3090ac638.jpg)

**Comment by siweia** [comment]
没有

**Comment by siweia** [comment]
你可以装一个ndui_plus，里面好像有
