### ISSUE TITLE
skada wrath skin

### ISSUE THREAD

**Issue by Flokj** [siweia/NDui#233]
`wrath`

what version Skada skin this button? 
![image](https://user-images.githubusercontent.com/99548130/215370635-c035adc8-e951-45fb-a758-1e4035186b59.png)

I found only this version for wrath
https://www.curseforge.com/wow/addons/skadarev
https://github.com/bkader/Skada-Damage-Meter

**Comment by siweia** [comment]
Only supports the official version atm. I will take a look the other fan updates.

**Comment by siweia** [comment]
Don't use those versions, they are only for private servers. Not for wrath classic by blizzard.
https://www.curseforge.com/wow/addons/skada-dragon-flight
The version above support wrath classic.
