### ISSUE TITLE
action totem bar

### ISSUE THREAD

**Issue by Flokj** [siweia/NDui#234]
`wrath`

![image](https://user-images.githubusercontent.com/99548130/215533055-e9d931e3-b108-4bef-8e12-099e38651fa6.png)
![image](https://user-images.githubusercontent.com/99548130/215533318-f5cc1ae8-22ef-483e-a2bc-55b532a13011.png)
action bar -> totem bar dont work
last version

**Comment by siweia** [comment]
1.Reset your totembar mover anchor.
2.Working fine, make sure its not switch off.
3.Design to be that anchor.

**Comment by Flokj** [comment]
1. thanks
2. I just can't find the setting, where it is?)))
3. ![image](https://user-images.githubusercontent.com/99548130/215763670-60aaaab7-ed8f-4563-8293-2d317fc45823.png)

**Comment by siweia** [comment]
Read the FAQ.
