### ISSUE TITLE
10.0.5 版本(NDui-7.5.0)小bug

### ISSUE THREAD

**Issue by zzyrd** [siweia/NDui#240]
更新了最新的ndui后，一切都还好。今天登录游戏突然姓名版，头像框，小地图，施法条等等都无法加载ndui的模块了。截图如下
![WoWScrnShot_031123_110607](https://user-images.githubusercontent.com/16825032/224494894-e68339d5-d8f2-421e-99fb-b55db4e492ba.jpg)

**Comment by zzyrd** [comment]
找到问题了。我更新了这个插件Premade Groups Filter(PremadeGroupsFilter-3.7.2)之后ndui就出问题了，可能是兼容性冲突？

**Comment by Zeddicus40** [comment]
I've found that rolling back "Premade Group Filter" addon to version 3.7.1 fix the issues with NDui

**Comment by 0xbs** [comment]
Version 3.7.2 to 3.7.3 did changes in tooltips and also fixed a typo: UsePFGButton is now named UsePGFButton. I saw that you already changed the code, so everything should be fine again. Sorry for the additional work on your end!
