### ISSUE TITLE
[bug?] /way no longer working like it used to.

### ISSUE THREAD

**Issue by JourneyOver** [siweia/NDui#245]
Pretty much title. I used to be able to do for example `/way XCords YCords` or `/way XCords, YCords` and it would put up a pin at that waypoint location automatically but for some reason now doing either just prints it out in chat and then I have to click the link thing it creates to actually get it to create the pin.

I have determined it is NDui that is causing this issue, as disabling NDui it reverts back to the old method of automatically creating the pin.

**Comment by siweia** [comment]
Are there any addons provide /way commands other than Tomtom?

**Comment by JourneyOver** [comment]
You are correct about the no addon it removes the `/way` command, The only other addon I have that does `/way` is https://www.curseforge.com/wow/addons/unlimited-map-pin-distance but even with it disabled NDui's `/way` is not working as intended..

I don't think you fully understood what I meant either..

Example: Before with just NDui I could put `/way 10, 10` and it would automatically place the pin at waypoint 10, 10 without me having to do anything extra, but now if I put `/way 10, 10` all it does it output a chat hyperlink 
![05-06-2023_09-46-25](https://user-images.githubusercontent.com/13910285/236631222-b95d16e8-d0de-4fda-8f33-62c7451c0359.png)
like so which then I have to click to get the pin to be placed. It does it regardless of what waypoints I put in I just used `10, 10` as an example.

**Comment by siweia** [comment]
Print and pin is the 'solution' in ndui. You can track multi locations in the same time by clicking different links.

**Comment by siweia** [comment]
https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Misc/Misc.lua#L571
I will disable mine when all the relevant addons loaded.

**Comment by JourneyOver** [comment]
> Print and pin is the 'solution' in ndui. You can track multi locations in the same time by clicking different links.

it used to be different though in that it automatically created the pin as I used to not have any other addon that messed with `/way` until recent and it would always automtically create the pin after I put in `/way xcord ycord` without me having to click links.. but whatever, guess best solution would be to just to do a check for https://www.curseforge.com/wow/addons/unlimited-map-pin-distance as well like tomtom.

**Comment by siweia** [comment]
It only means there are more addons use that cmd.

**Comment by JourneyOver** [comment]
@siweia Tested out the fix you put into place and it is not working, NDui is still overridding `/way` making it just put the coords link into chat instead of making an actual pin. Only reliable fix that I have actually found was just going back to the old method and adding `or IsAddOnLoaded("UnlimitedMapPinDistance")` to the line.

**Comment by siweia** [comment]
But working on mine.

**Comment by JourneyOver** [comment]
> But working on mine.

I tested it with only `NDui` and `UnlimitedMapPinDistance` to make sure that there was no other addon making a conflict and it was still only printing it to chat so not sure how it is only "working" on your end.

I do see that you made another commit to auto track map pin while still printing to chat, tested it and it's at least working so I guess that's at least a solution to this problem.

**Comment by siweia** [comment]
Not sure. I did the same with ndui and UMPD enabled only.
