### ISSUE TITLE
A small problem with my Garrison

### ISSUE THREAD

**Issue by Sephiroth105** [siweia/NDui#25]
...terface\FrameXML\FloatingGarrisonFollowerTooltip.lua:388: attempt to get length of field 'Properties' (a nil value)
Count: 2

Call Stack:
[C]: ?
...terface\FrameXML\FloatingGarrisonFollowerTooltip.lua:388: in function <...terface\FrameXML\FloatingGarrisonFollowerTooltip.lua:319>
[C]: in function `GarrisonFollowerTooltipTemplate_SetShipyardFollower'
Interface\FrameXML\GarrisonFollowerTooltip.lua:42: in function <Interface\FrameXML\GarrisonFollowerTooltip.lua:32>
[C]: in function `GarrisonFollowerTooltip_ShowWithData'
Interface\FrameXML\GarrisonFollowerTooltip.lua:29: in function `GarrisonFollowerTooltip_Show'
...\Blizzard_GarrisonUI\Blizzard_GarrisonShipyardUI.lua:2191: in function <...\Blizzard_GarrisonUI\Blizzard_GarrisonShipyardUI.lua:2180>
[C]: ?

**Comment by siweia** [comment]
This error belongs to the Blizzard's addons, it might popup even without addon enabled.
You can just simply ignore it.
