### ISSUE TITLE
RaiderIO Skin Bug

### ISSUE THREAD

**Issue by DakJaniels** [siweia/NDui#258]
Interface/AddOns/RaiderIO/core.lua:1267: Raider.IO Config expects Get(key[, fallback]) to only be used after the addon saved variables have been loaded.
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: in function `assert'
[string "@Interface/AddOns/RaiderIO/core.lua"]:1267: in function `Get'
[string "@Interface/AddOns/RaiderIO/core.lua"]:5726: in function <Interface/AddOns/RaiderIO/core.lua:5725>
[string "@Interface/AddOns/RaiderIO/core.lua"]:63: in function <Interface/AddOns/RaiderIO/core.lua:62>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:178: in function <Interface/SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:222: in function `SetScrollTargetOffset'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:714: in function <Interface/SharedXML/Scroll/ScrollBox.lua:696>
[string "=[C]"]: in function `Update'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:135: in function <Interface/SharedXML/Scroll/ScrollBox.lua:129>
[string "=[C]"]: in function `GetWidth'
[string "@Interface/AddOns/NDui/Core/Functions.lua"]:1041: in function `ReskinTrimScroll'
[string "@Interface/AddOns/NDui/Modules/Skins/Blizzard/FrameXML/FriendsFrame.lua"]:144: in function `func'
[string "@Interface/AddOns/NDui/Modules/Skins/Skins.lua"]:33: in function `LoadAddOnSkins'
[string "@Interface/AddOns/NDui/Modules/Skins/Skins.lua"]:60: in function `OnLogin'
[string "@Interface/AddOns/NDui/Init.lua"]:136: in function `func'
[string "@Interface/AddOns/NDui/Init.lua"]:23: in function <Interface/AddOns/NDui/Init.lua:18>

**Comment by siweia** [comment]
Should be issue on raider io. NDui never skin any parts from it.

**Comment by JourneyOver** [comment]
Just to note that your fixes didn't actually fix the error that was mentioned above as running the latest version and it still throws the same error, but I had created an issue on raiderio github page a few weeks back and they came up with a solution as of recent made in this commit https://github.com/RaiderIO/raiderio-addon/commit/dba042f0883d04cd20c5287b684e2b4e1a44528f which fixes the lua error.
