### ISSUE TITLE
[Classic] Aurawatch cannot show custom spell ids

### ISSUE THREAD

**Issue by AngelosNaoumis** [siweia/NDui#262]
When adding a custom spell ID in aurawatch on classic it does not show up.

When doing it with LUA it does show up.

From GUI settings you can only add to Custom CD.

**Comment by siweia** [comment]
How did you do in LUA? Can you post it here?

**Comment by AngelosNaoumis** [comment]
Just go directly to file and add the spell there  Interface\AddOns\NDui\Config\AuraWatchList and add my spells there

**Comment by LvMingfei** [comment]
比如萨满的石化武器(ID：10399)，无论是AuraID还是SpellID添加监听后都不生效。
另外右上角的buff框体里，萨满武器附魔的时间显示也不对

**Comment by AngelosNaoumis** [comment]
From lua i do not have issues I can add my spells.

The issue is only for UI ingame (add any spell and it will not work)

**Comment by siweia** [comment]
Just do as I told!
Once you post your edit in here, I can tell why you cant add in ui. And tell me how you did in game ui might be helpful as well.
There shouldn't be any issue in the ui itself.
So what is the difficulty among the conversation for talking such a long period?
