### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by heyner88** [siweia/NDui#263]
Hi I'm getting this error every time I queue for raid, dungeon, only happens when NDui is enabled

Message: Interface/FrameXML/MainMenuBarMicroButtons.lua:1623: attempt to compare two nil values
Time: Sun Mar 31 10:25:45 2024
Count: 2
Stack: Interface/FrameXML/MainMenuBarMicroButtons.lua:1623: attempt to compare two nil values
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1623: in function `GetEdgeButton'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1651: in function `UpdateHelpTicketButtonAnchor'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1710: in function `Layout'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1759: in function `Layout'
[string "@Interface/FrameXML/QueueStatusFrame.lua"]:276: in function <Interface/FrameXML/QueueStatusFrame.lua:268>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/QueueStatusFrame.lua"]:656: in function <Interface/FrameXML/QueueStatusFrame.lua:493>
[string "=[C]"]: in function `Update'
[string "@Interface/FrameXML/QueueStatusFrame.lua"]:433: in function <Interface/FrameXML/QueueStatusFrame.lua:432>

Locals: self = MicroMenu {
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 GetEdgeButton = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1600
 ShouldUpdateLayout = <function> defined @Interface/SharedXML/LayoutFrame.lua:483
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:99
 SetHeightPadding = <function> defined @Interface/SharedXML/LayoutFrame.lua:160
 layoutFramesGoingRight = true
 OnCleaned = <function> defined @Interface/SharedXML/LayoutFrame.lua:131
 isHorizontal = true
 OnUpdate = <function> defined @Interface/SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @Interface/SharedXML/LayoutFrame.lua:85
 GetFixedSize = <function> defined @Interface/SharedXML/LayoutFrame.lua:156
 OnShow = <function> defined @Interface/SharedXML/LayoutFrame.lua:32
 GetHeightPadding = <function> defined @Interface/SharedXML/LayoutFrame.lua:164
 UpdateFramerateFrameAnchor = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1666
 GetFixedWidth = <function> defined @Interface/SharedXML/LayoutFrame.lua:148
 dirty = false
 stride = 12
 GetWidthPadding = <function> defined @Interface/SharedXML/LayoutFrame.lua:168
 childYPadding = -5
 SetScaleAdjustment = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1713
 layoutFramesGoingUp = false
 UpdateQueueStatusAnchors = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1656
 SetFixedWidth = <function> defined @Interface/SharedXML/LayoutFrame.lua:135
 InitializeButtons = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1565
 GetFixedHeight = <function> defined @Interface/SharedXML/LayoutFrame.lua:152
 MarkClean = <function> defined @Interface/SharedXML/LayoutFrame.lua:117
 CacheLayoutSettings = <function> defined @Interface/SharedXML/LayoutFrame.lua:471
 SetFixedSize = <function> defined @Interface/SharedXML/LayoutFrame.lua:143
 GetLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:73
 numButtons = 12
 IsDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:127
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1560
 oldGridSettings = <table> {
 }
 Layout = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1703
 SetFixedHeight = <function> defined @Interface/SharedXML/LayoutFrame.lua:139
 AnchorToMenuContainer = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1674
 SetQueueStatusScale = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1695
 0 = <userdata>
 UpdateHelpTicketButtonAnchor = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1634
 AddButton = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1591
 MarkIgnoreInLayout = <function> defined @Interface/SharedXML/LayoutFrame.lua:44
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:55
 childXPadding = -5
 IgnoreLayoutIndex

**Comment by siweia** [comment]
should have beenfixed in recent commits

**Comment by heyner88** [comment]
Thank you it seems it fine now 👍 

Also i want to add as a side note that when the server name has more than one word like Emerald Dream the gold in the infobar doesn't show the gold for each char in the server for fix this I added the following code in the file Gold.lua at the line 25 
local myRealm = myRealm:gsub(" ", "")

thank again your for your great work :)

**Comment by siweia** [comment]
i think the realm thing is fixed as well.

**Comment by heyner88** [comment]
yep everything is working great know thank you 👍
