### ISSUE TITLE
Krowi's Achievement Filter skin, black criteria text for achievements that are won

### ISSUE THREAD

**Issue by JourneyOver** [siweia/NDui#265]
Pretty much the title, I'm not sure how long this has been going on for exactly as I just got back into playing after taking a decent break during season 3 after my guild slowed down on raiding, but anyways it seems like there is a slight issue with the skin for Krowi's Achievement filter, in that for the criteria text for gained achievements seem to just be straight black as shown in the pictures:
![image](https://github.com/siweia/NDui/assets/13910285/53e782df-cb27-47f4-98cd-857d01b59fb5)
![image](https://github.com/siweia/NDui/assets/13910285/fa021aec-dc45-4ae8-8530-ca37faf3bf75)

There are some others as well where if I click on the achievement the text turns white until I either click on it again or click on a different achievement. like:
![image](https://github.com/siweia/NDui/assets/13910285/805614e9-c314-4b19-8bd7-5ad55eba4b88)

Ones that are not already achieved seem to work correctly however:
![image](https://github.com/siweia/NDui/assets/13910285/53bf6ca2-2f06-4607-b9b6-00e83ec0c79f)

**Comment by JourneyOver** [comment]
Also if at all possible to add onto this issue with a skin request for [Rarity](https://www.curseforge.com/wow/addons/rarity) (Specifically the popup bit 
![image](https://github.com/siweia/NDui/assets/13910285/508b1ddd-804f-418d-86bf-0678822962f4)
) (Mostly due to the black text issue as well with it) I can ask @Witnesscm about this bit though if need be but I do want to see the above issue at least fixed)

**Comment by JourneyOver** [comment]
@siweia so `Krowi's Achievement Filter` is semi-fixed in the commit https://github.com/siweia/NDui/commit/6bff24f26126c472fd04a1ec417ae979fbee8239 the only ones that are still broken are the achievements like ![image](https://github.com/siweia/NDui/assets/13910285/805614e9-c314-4b19-8bd7-5ad55eba4b88) (The text stays black still until you click on it then it turns white until you either click on it again or click on a different achievement)

**Comment by JourneyOver** [comment]
Looks like 5b9f125 has fixed it all for now, can close this issue if you want unless you plan on doing the rarity thing as well :o

**Comment by siweia** [comment]
I don't use rarity at all. Is there a command that can popout a notification for me to get start?
