### ISSUE TITLE
How do I move the Dragonriding Vigor bubbles.

### ISSUE THREAD

**Issue by D2junkie** [siweia/NDui#266]
Even with the check box checked for "Encounter Bar" within the Edit Mode I'm unable to move the vigor bar. Am I missing where I would be able to adjust this placement?

**Comment by siweia** [comment]
Read FAQ.

**Comment by D2junkie** [comment]
Q: I find a problem that a...
A: Make sure you know the options from GUI panel and the slash cmd list from /ndui.

Q: How to change opacity of UI? How to disable the font outlines?
A: GUI-Skins.

Q: How to setup the spells on pensonal resource bar?
A: Search folder "Lumos" and find your own class, it can only be changed in LUA files.

Q: How to compare items?
A: Hold shift key. Or auto compare via "/run SetCVar("alwaysCompareItems", 1)".

Q: Can I modify the unitframes or actionbars?
A: Disable the features in GUI panel, and use your own addon.

Q: How to tell whether the castbars interruptable or not?
A: Blue color: interruptable, red color: not interruptable.

Q: Minimap tracker and calendar?
A: Right click minimap to toggle tracker, scroll button click to toggle calendar.

Q: How to toggle auto repair, auto sell junk?
A: Check with your infobar tooltips.

Q: How to scroll chat frame to top or bottom?
A: Hold shift and scroll.

Q: Loot banner after encounter end? Talking header for quests?
A: Go check the GUI panel in section MISC.

Q: How to invite a unit to party or guild?
A: ALT+LeftButton=Invite unit, CTRL+LeftButton=Guild invite, SHIFT+LeftButton=Copy name.

I don't see anything in there that talks about moving the vigor bubbles.

**Comment by siweia** [comment]
A: Make sure you know the options from GUI panel and the slash cmd list from /ndui.

**Comment by D2junkie** [comment]
Oh gosh, I was looking for the wrong name. Thank you!
