### ISSUE TITLE
能否改进一下背包分类

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#27]
比如去刷幻化，刷了一堆低级装备和包里的当前版本装备都混一起了，卖店卖半天还容易卖错，现在的新物品闪光辨识度不够
能否让低级装备(比如ilvl<266)不进入装备分类，新增一个分类或者直接进入底层的主背包，或者直接像cargBags_Nivaya那样，新获得的东西都暂时放在一个新分类里

**Comment by siweia** [comment]
这种情况，可以使用装备方案的分类，来替换装备分类。
