### ISSUE TITLE
11.0 err

### ISSUE THREAD

**Issue by fredako** [siweia/NDui#270]
only NDUI and in Dungeon.

`290x NDui/Modules/Auras/Reminder.lua:57: attempt to call upvalue 'UnitBuff' (a nil value)
[string "@NDui/Modules/Auras/Reminder.lua"]:57: in function `Reminder_Update'
[string "@NDui/Modules/Auras/Reminder.lua"]:104: in function `func'
[string "@NDui/Init.lua"]:23: in function <NDui/Init.lua:18>

Locals:
self = <table> {
 IgnoredItems = <table> {
 }
 PrivateFrame = NDuiPrivateAuras {
 }
 DebuffFrame = NDuiPlayerDebuffs {
 }
 settings = <table> {
 }
 name = "Auras"
 PrivateAuras = <table> {
 }
 BuffFrame = NDuiPlayerBuffs {
 }
 PetBattleFrameHider = Frame {
 }
}
cfg = <table> {
 depend = 364342
 spells = <table> {
 }
 frame = Frame {
 }
 instance = true
}
frame = Frame {
 __shadow = Frame {
 }
 PixelSnapDisabled = true
 text = FontString {
 }
 bg = Frame {
 }
 Icon = Texture {
 }
}
depend = 364342
spec = nil
combat = nil
instance = true
pvp = nil
itemID = nil
equip = nil
inGroup = nil
isPlayerSpell = true
isRightSpec = true
isEquipped = true
isGrouped = true
isInCombat = nil
isInInst = true
isInPVP = nil
inInst = true
instType = "party"
weaponIndex = nil
(for index) = 1
(for limit) = 32
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'UnitBuff' (a nil value)"
IsEquippedItem = nil
GetItemCooldown = nil
UnitBuff = nil`

**Comment by siweia** [comment]
fixed in recent commits.
