### ISSUE TITLE
幻彩模式，猎人这个职业加载不出来完全的美化界面

### ISSUE THREAD

**Issue by tppioneer** [siweia/NDui#271]
World of Warcraft\_retail_\Interface\AddOns\NDui\Modules\Skins\Blizzard\FrameXML
文件名PetStable.lua
12~18行需要增加PetStableBottomInset 等的是否可用的判断，
以下代码：
  if PetStableBottomInset != "nil" then
    PetStableBottomInset:Hide()
    PetStableLeftInset:Hide()
    PetStableFrameModelBg:Hide()
    PetStablePrevPageButtonIcon:SetTexture("")
    PetStableNextPageButtonIcon:SetTexture("")
    PetStableDietTexture:SetTexture(132165)
    PetStableDietTexture:SetTexCoord(x1, x2, y1, y2)
  end

**Comment by siweia** [comment]
先学会更新插件。这个文件早就移除了
