### ISSUE TITLE
请求团队框架点击施法增加打开菜单功能

### ISSUE THREAD

**Issue by glennliu16** [siweia/NDui#273]
你好，

我本人是习惯左键选择目标，右键菜单。然后用其他鼠标按键在团队框架上点击施法。

根据你在插件上面的instruction，可以实现选择目标的功能，但是我尝试/menu字符却不能实现菜单功能。

我非常你能增加菜单功能，这样我就不必使用暴雪自带的点击施法或者clique了。

谢谢

**Comment by siweia** [comment]
默认就是右键打开菜单，别设置右键技能不就是右键打开菜单了？

**Comment by glennliu16** [comment]
> 默认就是右键打开菜单，别设置右键技能不就是右键打开菜单了？

你好，只有在关闭团队框架点击施法的时候才能使用右键打开菜单。而在启用团队框架点击施法的时候，就算右键没有设置任何技能也无法使用右键打开菜单。这就是我为什么提交问题的原因。

**Comment by siweia** [comment]
我这边试了一切正常。右键不设置技能是不影响右键菜单的

**Comment by glennliu16** [comment]
你好，我把所有插件重新安装一次，发现没有设置技能默认右键菜单的功能正常运作了，谢谢。
