### ISSUE TITLE
[Feature Request] Gradient Colors

### ISSUE THREAD

**Issue by AngelosNaoumis** [siweia/NDui#276]
Hey,

Would love to request a custom class color gradient implementation (50% color A, 50% color B)

API:
https://wowpedia.fandom.com/wiki/ColorGradient

e.g.
From Eltriusm
![image](https://github.com/user-attachments/assets/aa773310-6a8a-43cf-a784-ecb6d7824b8f)
![image](https://github.com/user-attachments/assets/a1682772-6224-4ec3-ba02-2993bbf713f7)

**Comment by siweia** [comment]
You can use gradient classcolor for unitframes in GUI.

**Comment by AngelosNaoumis** [comment]
This goes from class color to transparent gradient.

It would be awesome if we can have 2 different colors.
