### ISSUE TITLE
Currency Transfer does not work.

### ISSUE THREAD

**Issue by Varthx** [siweia/NDui#279]
When trying to transfer warband currency, getting an NDui blocks this action error.

Server is down currently or I would try and grab what the error says.

**Comment by siweia** [comment]
Works fine on ptr server.

**Comment by Varthx** [comment]
ill see if its a addon conflict on my end. I have buggrabber and bugsack now. so let me see if it grabs the error.

**Comment by Varthx** [comment]
2x [ADDON_ACTION_FORBIDDEN] AddOn 'NDui' tried to call the protected function 'RequestCurrencyFromAccountCharacter()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `RequestCurrencyFromAccountCharacter'
[string "@Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua"]:331: in function <...ddOns/Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua:328>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}


This is all it gave me, playing on Live currently.

**Comment by siweia** [comment]
try with ndui only

**Comment by Varthx** [comment]
Just tried it with NDui only, after reload it works once and then when I try to do it again on the same currency I get an error. If i try it on another currency it still gives me an error.

**Comment by siweia** [comment]
Should be fixed in recent commits.
