### ISSUE TITLE
Warband bank missing gold amount withdrawal and deposit

### ISSUE THREAD

**Issue by Varthx** [siweia/NDui#280]
![image](https://github.com/user-attachments/assets/2f0ce05b-ee61-4cf6-b01d-27ccc64cc575)

This is currently missing from the NDui warband interface.

**Comment by Varthx** [comment]
Ah I see it only shows up if there is actual value in there. I would recommend showing a 0 and the gold symbol when there is nothing in the warband as its gone with nothing there.

**Comment by siweia** [comment]
Fixed in recent commits.
