### ISSUE TITLE
大佬 这几个错误是我哪里设置的不对么

### ISSUE THREAD

**Issue by 393306235** [siweia/NDui#283]
2x [ADDON_ACTION_FORBIDDEN] 插件 'NDui' 尝试调用保护功能 'UseQuestLogSpecialItem()'。
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

1x [ADDON_ACTION_BLOCKED] 插件 'NDui' 尝试调用保护功能 'MultiBarBottomRight:SetPointBase()'。
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPointBase'
[string "@Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua"]:138: in function `SetPoint'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:602: in function `UpdateBottomActionBarPositions'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:508: in function `UpdateActionBarLayout'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:357: in function `UpdateVisibility'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:324: in function `Hide'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:172: in function `Update'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:512: in function `OnIconLeave'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:704: in function <...rd_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:703>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

161x ...Dui/Libs/LibActionButton-1.0/LibActionButton-1.0.lua:2360: attempt to call global 'IsSpellInRange' (a nil value)
[string "@NDui/Libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:2360: in function `IsUnitInRange'
[string "@NDui/Libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:2272: in function `IsInRange'
[string "@NDui/Libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:1473: in function <...Dui/Libs/LibActionButton-1.0/LibActionButton-1.0.lua:1456>

Locals:
self = LABFlyoutButton5 {
 FlyoutBorderShadow = LABFlyoutButton5FlyoutBorderShadow {
 }
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 LevelLinkLockIcon = Texture {
 }
 Flash = LABFlyoutButton5Flash {
 }
 TargetReticleAnimFrame = Frame {
 }
 _state_action = 383363
 icon = LABFlyoutButton5Icon {
 }
 SlotArt = Texture {
 }
 InterruptDisplay = Frame {
 }
 rangeTimer = -1
 __bg = Frame {
 }
 __styled = true
 HotKey = LABFlyoutButton5HotKey {
 }
 HighlightTexture = Texture {
 }
 action = 0
 AutoCastOverlay = Frame {
 }
 flashing = 0
 SpellCastAnimFrame = Frame {
 }
 CooldownFlash = Frame {
 }
 state_actions = <table> {
 }
 IconMask = MaskTexture {
 }
 TextOverlayContainer = Frame {
 }
 state_types = <table> {
 }
 header = LABFlyoutHandlerFrame {
 }
 PushedTexture = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 CheckedTexture = Texture {
 }
 Border = LABFlyoutButton5Border {
 }
 id = 5
 SpellHighlightTexture = Texture {
 }
 __LAB_Version = 110
 NormalTexture = LABFlyoutButton5NormalTexture {
 }
 config = <table> {
 }
 Name = LABFlyoutButton5Name {
 }
 _state_type = "spell"
 SlotBackground = Texture {
 }
 Count = LABFlyoutButton5Count {
 }
 cooldown = LABFlyoutButton5Cooldown {
 }
 zoneAbilityDisabled = false
}
unit = nil
slot = 50
(*temporary) = nil
(*temporary) = 50
(*temporary) = "spell"
(*temporary) = nil
(*temporary) = "attempt to call global 'IsSpellInRange' (a nil value)"

5x ...ceNDui/Libs/cargBags/base/implementation.lua:99: attempt to call global 'CloseBankFrame' (a nil value)
[string "@NDui/Libs/cargBags/base/implementation.lua"]:99: in function `?'
[string "@NDui/Libs/cargBags/base/core.lua"]:157: in function <NDui/Libs/cargBags/base/core.lua:157>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@NDui/Libs/cargBags/base/core.lua"]:75: in function `CloseAllBags'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:1118: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:1117>
[string "=[C]"]: in function `securecall'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2842: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = NDui_Backpack {
 buttons = <table> {
 }
 contByName = <table> {
 }
 numSlots = 368
 buttonClass = <table> {
 }
 contByID = <table> {
 }
 events = <table> {
 }
 bagSizes = <table> {
 }
 name = "NDui_Backpack"
}
(*temporary) = nil
(*temporary) = "attempt to call global 'CloseBankFrame' (a nil value)"

**Comment by siweia** [comment]
提问之前先看看自己插件更新了没有。还在用着几个月前的版本
