### ISSUE TITLE
请问可否为“全局字体描边”功能添加加粗选项？

### ISSUE THREAD

**Issue by zad931228** [siweia/NDui#284]
如题，目前的全局字体描边只有较细(参考其他插件应该是outline?)的描边，希望可以添加更粗一些的选择(参考替他插件的thick?)
备注：这次回归暂未使用NDui，不确认是否已经包含此功能，如已添加向您道歉

**Comment by siweia** [comment]
暴雪API的Outline一直都只有一种，不存在thick或者thin
你如果觉得变细了，可能是你换了更好的显示器。
比如以前用1080P，2K，现在用4K，就会觉得变“细”了

**Comment by zad931228** [comment]
> 暴雪API的Outline一直都只有一种，不存在thick或者thin 你如果觉得变细了，可能是你换了更好的显示器。 比如以前用1080P，2K，现在用4K，就会觉得变“细”了
您好，可能是我的表述有不清楚的地方：比如plater或details的字体描边可以设置为none/outline/thick，我希望NDui的全局字体描边功能可以开放多种描边粗细的选项供选择
