### ISSUE TITLE
Item level is no longer displayed on the default bags.

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#287]
### Bug Report: Item Level Display Issue

**Expansion:** The War Within  
**Faction:** Horde  
**Class:** Orc Hunter

**Issue:**  
If you disable the `Bags Consolidated` option in `NDui -> Bags -> Enable Bags Consolidated`, the default bags no longer display item level on items.

**Steps to Reproduce:**
1. Go to `NDui -> Bags -> Enable Bags Consolidated`.
2. Disable the `Bags Consolidated` option.
3. Open the default bags.
4. Notice that the item level is no longer displayed on items.

**Expected Behavior:**  
Item level should be displayed on items in the default bags, even when the `Bags Consolidated` option is disabled.

![image](https://github.com/user-attachments/assets/2fdf0030-f3c8-4e10-a5a7-e185378d6715)

**Comment by siweia** [comment]
Should be fixed in recent commits.
