### ISSUE TITLE
Reagent Bag

### ISSUE THREAD

**Issue by Volarac** [siweia/NDui#289]
I'm not sure if something has changed or not with the bag filters.  I no longer have a reagents section and a reagents bag section, everything is just the reagent bag.  I have a character that does not have a reagent bag that has reagents in their bags and they are not appearing at all in my bags.  If I go into the bag options and shut off the Filter trade goods, then all the items appear.  When I turn it back on the items disappear.

On my main character with a reagent bag, I have a 26 slot reagent bag and I have 60 different reagents and they are all showing under the Reagent bag in my bags sections.

My version is 8.2.0 (TWW)

**Comment by siweia** [comment]
Reagents are now combine with reagent bag, which in on purpose.
And reagents missing for those character without reagent bag, has been fixed in recent commits.
