### ISSUE TITLE
LUA Error in latest version

### ISSUE THREAD

**Issue by Siodar** [siweia/NDui#290]
Message: Interface/AddOns/NDui/Core/GUI.lua:1172: attempt to concatenate field 'ShowGlow' (a nil value)
Time: Mon Sep  9 13:38:40 2024
Count: 1
Stack: Interface/AddOns/NDui/Core/GUI.lua:1172: attempt to concatenate field 'ShowGlow' (a nil value)

Locals: 

and there is no ndui button anymore in the menu.
![image](https://github.com/user-attachments/assets/6df72585-1012-4b19-bf38-3485171eac09)
 have uninstalled and reinstalled, also exit and reloaded game.

**Comment by Enestra** [comment]
Huhu habe den gleiche LUA Fehler  bitte um Hilfe..
