### ISSUE TITLE
Request: Can you add an Ilvl filter to the bags, so if above a certain ilvl it separates the gear into a different section of the bag

### ISSUE THREAD

**Issue by Varthx** [siweia/NDui#297]
Would love a feature as described in the title. as someone who likes to run old content it would be nice for that old gear to move to a different section of the bag so when selling it I don't accidently sell current gear I want to keep.

**Comment by siweia** [comment]
There is a feature to modify ilvl gap in your bags.

**Comment by Varthx** [comment]
I have made the changes to NDui to add this functionality but I cant create a branch for you to look at it.

**Comment by Varthx** [comment]
for now i have forked it so you can see the changes https://github.com/Varthx/NDui/tree/EquipmentThreshold

**Comment by Varthx** [comment]
thanks, your solution is much more elegant! my first day working in Lua though! :P
