### ISSUE TITLE
Action bars and rune bars have dissapeared

### ISSUE THREAD

**Issue by blakesimpson-dev** [siweia/NDui#298]
Action bars and rune bars have dissapeared

**Comment by siweia** [comment]
version?

**Comment by blakesimpson-dev** [comment]
NDuiClassic 4.5.1

 Classic 1.15.5.56760

**Comment by siweia** [comment]
There isn't any 1.15.5.56760, and only 1.15.4.56760.
And check your actionbar settings provided by blizzard.
