### ISSUE TITLE
8.1 以后暴雪自己的 ChatFrame.lua 频繁报错有办法解决么？

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#30]
时不时的出这个报错好烦，或者有什么办法屏蔽这个报错也行 😆 

![wowscrnshot_010719_220908](https://user-images.githubusercontent.com/156806/50774253-ea4cad00-12cd-11e9-806d-f835c02772a2.png)

**Comment by siweia** [comment]
你有办法让他百分比出现吗？我玩这么久好像就遇过一次

**Comment by Solor** [comment]
对我来说出现的情况完全是随机，玩1个小时能出现3-4次，比较常见的是点开战争前线排队的桌子，出现世界任务那个屏幕中间的banner，或者战争前线/世界任务的NPC喊话。

**Comment by siweia** [comment]
https://www.townlong-yak.com/framexml/live/ChatFrame.lua#1246
你有没使用castrandom宏

**Comment by siweia** [comment]
/castrandom 1
就报错了
所以检查你的随机XX宏

**Comment by Solor** [comment]
试了一下，确实是 userandom 和 castrandom 的问题，不使用就不会报错 🤣
