### ISSUE TITLE
Request: Can you add bar to select the nameplate top inset for insideview

### ISSUE THREAD

**Issue by Varthx** [siweia/NDui#300]
function UF:UpdatePlateCVars()
	if C.db["Nameplate"]["InsideView"] then
		SetCVar("nameplateOtherTopInset", .05) <-- I would personally like to set this value, just for refernece I like mine at .2 so maybe a slider between 0-1.
		SetCVar("nameplateOtherBottomInset", .08)
	elseif GetCVar("nameplateOtherTopInset") == "0.05" and GetCVar("nameplateOtherBottomInset") == "0.08" then
		SetCVar("nameplateOtherTopInset", -1)
		SetCVar("nameplateOtherBottomInset", -1)

**Comment by siweia** [comment]
It's better for you to disable the option, and modify the value personally.
Not a good idea to add too many options into GUI.
