### ISSUE TITLE
Possible memory leak in AuraWatch?

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#302]
AuraWatch On
![Wow_JW6Fhu8aUU](https://github.com/user-attachments/assets/95292ec2-2359-464d-9513-b91ed290b5ba)
![{C433D48A-DB10-4870-8CFA-7FFD52C40182}](https://github.com/user-attachments/assets/0857e01d-6c00-4700-8545-ced8ac42f354)
![{7DFA6274-4064-41DD-83E3-1D9B8211BD03}](https://github.com/user-attachments/assets/c14bb9c1-496d-4265-b79c-e46b31037ae8)

AuraWatch Off
![Wow_45K5NWHOv5](https://github.com/user-attachments/assets/191da50c-e6ab-4b25-9d61-2d5ef03b7f49)

**Comment by siweia** [comment]
just the issue with blizzard new aura system api
