### ISSUE TITLE
With todays update on EU seems to be broken

### ISSUE THREAD

**Issue by LifeIsBrilliant** [siweia/NDui#316]
Hi, unfortunately it seems NDui is currently broken. (at least for me)
Unfortunately there is no error captured in Bugsack
without NDui all addons/interfaces are working 
only NDui as addon same behaviour - no interaction with the game possible .. e.g. not even the game Menue can be opend.
Can move and run but no interactions with the interface.

Thank you for any hint

**Comment by Kostazu** [comment]
Seeing this also, NA region.  Bags, Quest, Shop, Talent buttons all work. Everything else from the menu bar does not. (hot keys for those options don't work either.)

**Comment by PunishedVsnake** [comment]
对，如同题主描述，NDUI似乎出现重大问题，多恩诺加尔地图左侧出现错误，游戏内与NPC的交互以及人物界面等快捷键无法启动
