### ISSUE TITLE
游戏版本更新后esc键异常

### ISSUE THREAD

**Issue by zhomm2013** [siweia/NDui#317]
在游戏更新到11.0.7后，首次进入游戏按esc键无法呼出系统菜单，已经排除了其他插件的问题，只有在禁用ndui之后才会恢复正常
或者打开要塞报告后，再按esc也可以恢复正常，但是一旦重新载入界面，esc再次失效。
并且系统菜单在第一次通过其他方式打开以后，esc也是正常运作，就是不能重载界面（重新安装ndui也无法解决）

**Comment by RRRick777** [comment]
11.07暴雪不但是内容更新还动了一些UI的代码导致和UI相关的插件适配都出问题了

**Comment by nanjuekaien1** [comment]
https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Maps/WorldMap.lua#L278
这行暂时 注销掉
内置预创建报错暂时解决办法
https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Misc/QuickJoin.lua#L121
改为：
local activityInfo = C_LFGList.GetActivityInfoTable(searchResultInfo.activityIDs[1], nil, searchResultInfo.isWarMode)

其他错误等大S出差回来修复。

**Comment by LifeIsBrilliant** [comment]
Thank you Nanjuekaien
works now with commenting out the line 278 in Worldmap.lua and changing the code in Quickjoin.lua as you wrote ..
Xiexie

**Comment by RRRick777** [comment]
> https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Maps/WorldMap.lua#L278 这行暂时 注销掉 内置预创建报错暂时解决办法 https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Misc/QuickJoin.lua#L121 改为： local activityInfo = C_LFGList.GetActivityInfoTable(searchResultInfo.activityIDs[1], nil, searchResultInfo.isWarMode)
> 
> 其他错误等大S出差回来修复。

暫時fixed! thx!
