### ISSUE TITLE
请教一下获取 SavedVariables 值的问题

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#32]
根据我的理解，在 NDUI 里只有在 `module:OnLogin()` 后才能获取 SavedVariables 表里的值

比如说直接 `print(NDuiDB["BFA"])` 结果是 `nil`
必须这样 
`function module:OnLogin()`
`print(NDuiDB["BFA"])`
`end` 
才能得到这个值为 `true`

但是有些代码并没有在 `module:OnLogin()` 里面也能成功获取 SavedVariables 表里的某个值，为啥呢，研究了很久没搞懂 😢

**Comment by siweia** [comment]
NDuiDB这个要在PLAYER_LOGIN之后才能获取到值，所以只要确保你获取时，晚于这个事件就可以了

**Comment by Solor** [comment]
https://github.com/siweia/NDui/blob/e24284eaa3feca15052ab8abee233d1345852447/Interface/AddOns/NDui/Modules/Tooltip/Tip.lua#L30

比如这个tooltip里的function，你并没有让它在 `PLAYER_LOGIN` 后执行，为啥它能得到 `NDuiDB["Tooltip"]["FactionIcon"]` 的值 ❓

**Comment by siweia** [comment]
因为执行hideLines的时候，已经是在这个事件之后了。

**Comment by Solor** [comment]
啊我明白了，hook gametooltip 的时候已经在 PLAYER_LOGIN 之后了
