### ISSUE TITLE
WardrobeTransmogFrame.SpecButton

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#37]
![world of warcraft screenshot 2019 02 08 - 23 01 05 85](https://user-images.githubusercontent.com/156806/52486488-3b65fe80-2bf6-11e9-8c58-6f4ec33b1dca.jpg)

**Comment by siweia** [comment]
你再检查一下，是不是漏了哪一行

**Comment by Solor** [comment]
半夜更新眼花了 🤣
