### ISSUE TITLE
suggestion - UI screen shot in github 

### ISSUE THREAD

**Issue by Urguk** [siweia/NDui#39]
Could you put a screen shot of your UI in the github front page.

**Comment by siweia** [comment]
I need to figure out how to do so first.

**Comment by Urguk** [comment]
Love the UI, I used it last night raid.

**Comment by Urguk** [comment]
I did find this to turn off the combat text over target on is dmg and the
other is for healing.

Link to Blizzard post  https://us.battle.net/support/en/article/46205

-- Turn off = 0 on = 1 Floating Combat over target
/console floatingCombatTextCombatDamage 1
/console floatingCombatTextCombatHealing 1
