### ISSUE TITLE
UIWidget里的进度条能不能美化一下

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#43]
[UIWidget](https://github.com/Shestak/ShestakUI/blob/master/ShestakUI/Modules/Skins/Blizzard/UIWidget.lua)

**Comment by siweia** [comment]
比如哪些地方

**Comment by Solor** [comment]
PVP里的区域占领进度条以及海岛的艾泽里特进度条

**Comment by 450717565** [comment]
大佬，那沙塔尔的深渊召唤1阶段的计时条没有美化。

**Comment by siweia** [comment]
不考虑。
