### ISSUE TITLE
Buff

### ISSUE THREAD

**Issue by Urguk** [siweia/NDui#50]
Buff duration do not show pass 1hr. For example Grim Visage is a 2 hour buff but on show 1hr. If I disable the UI the default show 2hr. This is for Darkmoon Fair Wheee! buff and flask with alchemy buff.

![image](https://user-images.githubusercontent.com/369974/67790797-bb661a00-fa4c-11e9-81fb-b7af0b9e19f2.png)

**Comment by siweia** [comment]
1h means 1h+.
2h means 2h+.

**Comment by Urguk** [comment]
Not sure what that comment mean. Two hour buff are not showing up as 2h.

**Comment by siweia** [comment]
If an aura's duration is between 1h and 2h, the text would be 1h.
If duration between 2h and 3h, the text would be 2h.
This is not a bug.
