### ISSUE TITLE
Option request

### ISSUE THREAD

**Issue by Urguk** [siweia/NDui#56]
For the Shaman Resto could the resource bar be removed and just have the Icon showing. Don't need to see my mana and heath as I can see it under my unit frame or raid frame. Now thinking about it could the unit frame also be hidden as a option too?

**Comment by siweia** [comment]
Not a fan on hidden frames.
And also, if I add fade in/out feature for unitframes, it will need more works to change other ui elements to fit for frames.
Not interested atm.

**Comment by Urguk** [comment]
Would you be able to tell me where the personal resource code is as I would
like to add few more shaman talent to it please.

**Comment by siweia** [comment]
It is in lumos folder, which all written in FAQ,

**Comment by Urguk** [comment]
Thank you I was able to see add what I wanted. Where I having issue at is
the personal resource bars. Looking to remove them or hide it as it not
necessary.

[image: image.png]
