### ISSUE TITLE
Bag causing FPS drop when hover over items too quickly?

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#67]
Not entirely sure where this comes from. This might just be something to deal with.

So when hovering over armor like going left and right on the items it drops my FPS by 30-40fps. This does not happen with the blizzard bags nor other bags addons. It only seems to happen with armor and like azerite gear and so on.

Provided below is a bit of proof showing this.

https://gfycat.com/necessaryjubilantarkshell

**Comment by siweia** [comment]
There is no way to fix this, unless I remove the item ID and item info (eg azerite armor).
And it has nothing to do with bags.

**Comment by Kkthnx** [comment]
Well, it is not a huge issue. I just figured I would report on it. Not like we sit and just hover over items all day. Keep up the amazing work!

**Comment by siweia** [comment]
I thought it was my problem, and I do have the fps drop as you do, when hover over items.
A moment ago, after I disable addon 'BagSync', the problem vanished.
