### ISSUE TITLE
moving raid / Groupe frames

### ISSUE THREAD

**Issue by Hackparadize** [siweia/NDui#68]
Hi !
First, I want to thank you for the work you have been able to provide on this interface!

However I have a small question / proposal with regard to the raid and group frames, it is well marked in your FAQ that we must disable the UI management of your interface to use the addons we want, however I find that what you made us agrees very well, but it is just not in the right place for a lot of people I think and I find it shame, suddenly in your next interface update think you add the fact of move these frames as the default blizzard frame?

**Comment by siweia** [comment]
I just don't get the reason why people ask for the method to move raid frames.

At the very first line in the FAQ:
Q: I find a problem that a...
A: Make sure you know the options from GUI panel and the slash cmd list from /ndui.

And also, each time you log into game, you would see a tips on chatframe that tells you to use that slash cmd as well.
