### ISSUE TITLE
FPS bog down in BGs

### ISSUE THREAD

**Issue by Firegodd** [siweia/NDui#69]
I don't have a bug for you but when in BGs I can not do anything because my frame rates go down to 2. Everything else is great. I really LOVE this UI. Please try to get this fixed.

**Comment by siweia** [comment]
Try to enable my addon only.

**Comment by Firegodd** [comment]
Nope anytime I get over 500Mb on my Add-ons it throws this error:

2276x NDui\Modules\Infobar\Memory.lua:60: script ran too long
[string "@NDui\Modules\Infobar\Memory.lua"]:60: in function <NDui\Modules\Infobar\Memory.lua:57>
[string "@NDui\Modules\Infobar\Memory.lua"]:75: in function <NDui\Modules\Infobar\Memory.lua:71>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
UpdateAddOnMemoryUsage = <function> defined =[C]:-1
memoryTable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
 99 = <table> {
 }
 100 = <table> {
 }
 101 = <table> {
 }
 102 = <table> {
 }
 103 = <table> {
 }
 104 = <table> {
 }
 105 = <table> {
 }
 106 = <table> {
 }
 107 = <table> {
 }
 108 = <table> {
 }
 109 = <table> {
 }
 110 = <table> {
 }
 111 = <table> {
 }
 112 = <table> {
 }
 113 = <table> {
 }
 114 = <table> {
 }
 115 = <table> {
 }
 116 = <table> {
 }
 117 = <table> {
 }
 118 = <table> {
 }
 119 = <table> {
 }
 120 = <table> {
 }
 121 = <table> {
 }
 122 = <table> {
 }
 123 = <table> {
 }
 124 = <table> {
 }
 125 = <table> {
 }
 126 = <table> {
 }
 127 = <table> {
 }
 128 = <table> {
 }
 129 = <table> {
 }
 130 = <table> {
 }
 131 = <table> {
 }
 132 = <table> {
 }
 133 = <table> {
 }
 134 = <table> {
 }
 135 = <table> {
 }
 136 = <table> {
 }
 137 = <table> {
 }
 138 = <table> {
 }
 139 = <table> {
 }
 140 = <table> {
 }
 141 = <table> {
 }
 142 = <table> {
 }
 143 = <table> {
 }
 144 = <table> {
 }
 145 = <table> {
 }
 146 = <table> {
 }
 147 = <table> {
 }
 148 = <table> {
 }
 149 = <table> {
 }
 150 = <table> {
 }
 151 = <table> {
 }
 152 = <table> {
 }
 153 = <table> {
 }
 154 = <table> {
 }
 155 = <table> {
 }
 156 = <table> {
 }
 157 = <table> {
 }
 158 = <table> {
 }
 159 = <table> {
 }
 160 = <table> {
 }
 161 = <table> {
 }
 162 = <table> {
 }
 163 = <table> {
 }
 164 = <table> {
 }
 165 = <table> {
 }
 166 = <table> {
 }
 167 = <table> {
 }
 168 = <table> {
 }
 169 = <table> {
 }
 170 = <table> {
 }
 171 = <table> {
 }
 172 = <table> {
 }
 173 = <table> {
 }
 174 = <table> {
 }
 175 = <table> {
 }
 176 = <table> {
 }
 177 = <table> {
 }
 178 = <table> {
 }
 179 = <table> {
 }
 180 = <table> {
 }
 181 = <table> {
 }
 182 = <table> {
 }
 183 = <table> {
 }
 184 = <table> {
 }
 185 = <table> {
 }
 186 = <table> {
 }
 187 = <table> {
 }
 188 = <table> {
 }
 189 = <table> {
 }
 190 = <table> {
 }
 191 = <table> {
 }
 192 = <table> {
 }
 193 = <table> {
 }
 194 = <table> {
 }
 195 = <table> {
 }
 196 = <table>

**Comment by siweia** [comment]
There is no way to get over 500MB if you enable my addons only.

**Comment by Firegodd** [comment]
Yes that is true. As I've said this is a bug you need to fix. I've posted the bug report for you. Please fix this issue. If you do I may become a patron. I really Love your UI and don't want to have to turn off addons everytime I go into BG's or doing world PvP. At least give us the option to turn off some Data/Info texts if we don't want them on, or replace them with different ones please. Oh also this is not my rig doing this either as I have 32Gigs of ram.

**Comment by siweia** [comment]
Back to begging, as I said, you need to figure out WHICH ONE of your addons cause the conflict.
And that's the reason I mentioned about memory above. It has nothing to do with memory taken itself.
You are not the only who using a memory-beast-liked addon, but none of them has the same issue as you do.
Even it is my issue, I still need the name of the specific addon.
Just to give you a clue,  raider.io may be the main issue for this.

**Comment by Firegodd** [comment]
That's the thing it's not just a specific add-on conflicting with yours. I've turned them all off with just your addon running with one more on with all of my addons. The game does fine that way, but as soon as the addon mem gets over 500Mb no matter what combo of addons are on it does this in PvP combat only. I don't know how much simpler I can explain this.

**Comment by siweia** [comment]
You are not listening, no one is having the issue but you.
If you need me to fix whatever the issue it is, you should at least show me the addon list on the memory infobar. So that I can tell which addon is occupied the usage the most, and reproduce the issue if lucky.
What you said above, just not helping.

**Comment by Firegodd** [comment]
Here is the error again then:

2276x NDui\Modules\Infobar\Memory.lua:60: script ran too long
[string "@NDui\Modules\Infobar\Memory.lua"]:60: in function <NDui\Modules\Infobar\Memory.lua:57>
[string "@NDui\Modules\Infobar\Memory.lua"]:75: in function <NDui\Modules\Infobar\Memory.lua:71>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
UpdateAddOnMemoryUsage = <function> defined =[C]:-1
memoryTable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
 99 = <table> {
 }
 100 = <table> {
 }
 101 = <table> {
 }
 102 = <table> {
 }
 103 = <table> {
 }
 104 = <table> {
 }
 105 = <table> {
 }
 106 = <table> {
 }
 107 = <table> {
 }
 108 = <table> {
 }
 109 = <table> {
 }
 110 = <table> {
 }
 111 = <table> {
 }
 112 = <table> {
 }
 113 = <table> {
 }
 114 = <table> {
 }
 115 = <table> {
 }
 116 = <table> {
 }
 117 = <table> {
 }
 118 = <table> {
 }
 119 = <table> {
 }
 120 = <table> {
 }
 121 = <table> {
 }
 122 = <table> {
 }
 123 = <table> {
 }
 124 = <table> {
 }
 125 = <table> {
 }
 126 = <table> {
 }
 127 = <table> {
 }
 128 = <table> {
 }
 129 = <table> {
 }
 130 = <table> {
 }
 131 = <table> {
 }
 132 = <table> {
 }
 133 = <table> {
 }
 134 = <table> {
 }
 135 = <table> {
 }
 136 = <table> {
 }
 137 = <table> {
 }
 138 = <table> {
 }
 139 = <table> {
 }
 140 = <table> {
 }
 141 = <table> {
 }
 142 = <table> {
 }
 143 = <table> {
 }
 144 = <table> {
 }
 145 = <table> {
 }
 146 = <table> {
 }
 147 = <table> {
 }
 148 = <table> {
 }
 149 = <table> {
 }
 150 = <table> {
 }
 151 = <table> {
 }
 152 = <table> {
 }
 153 = <table> {
 }
 154 = <table> {
 }
 155 = <table> {
 }
 156 = <table> {
 }
 157 = <table> {
 }
 158 = <table> {
 }
 159 = <table> {
 }
 160 = <table> {
 }
 161 = <table> {
 }
 162 = <table> {
 }
 163 = <table> {
 }
 164 = <table> {
 }
 165 = <table> {
 }
 166 = <table> {
 }
 167 = <table> {
 }
 168 = <table> {
 }
 169 = <table> {
 }
 170 = <table> {
 }
 171 = <table> {
 }
 172 = <table> {
 }
 173 = <table> {
 }
 174 = <table> {
 }
 175 = <table> {
 }
 176 = <table> {
 }
 177 = <table> {
 }
 178 = <table> {
 }
 179 = <table> {
 }
 180 = <table> {
 }
 181 = <table> {
 }
 182 = <table> {
 }
 183 = <table> {
 }
 184 = <table> {
 }
 185 = <table> {
 }
 186 = <table> {
 }
 187 = <table> {
 }
 188 = <table> {
 }
 189 = <table> {
 }
 190 = <table> {
 }
 191 = <table> {
 }
 192 = <table> {
 }
 193 = <table> {
 }
 194 = <table> {
 }
 195 = <table> {
 }
 196 = <table>

**Comment by JourneyOver** [comment]
> You are not listening, no one is having the issue but you.

@siweia

Actually that's not true, he isn't the only one having this issue of it lagging hard in battlegrounds.

I sadly haven't been able to pinpoint the exact addon myself because I can randomly disable any one of my addons and the lag would go away temporarily and then eventually come back until I disabled another addon (and I could end up re-enabling the one I disabled) and then it would repeat of the lag disappearing temporarily and then coming back again.

The one thing I don't get is the error that he is getting though.. so I'm not sure on that one, as I currently get no errors whatsoever.

If you would like I could zip up my WTF/Interface folder and send it to you and you could do some testing and maybe you could pinpoint the addon that could possibly be causing it?

**Comment by siweia** [comment]
@JourneyOver my email add: siweia@outlook.com

**Comment by JourneyOver** [comment]
@siweia WTF/Interface folders have been zipped up and sent to your email ^^

**Comment by Firegodd** [comment]
@JourneyOver Like I was saying it's not a specific addon causeing it. Just when the mem gets over 500Mb. I tryed all combos and they all did it when the mem got over 500Mb. What's wierd though is it would only happen in Bg's or instanced PvP content. @siweia I can screen shot my wtf folder for you so you can recreate it if you'd like?

**Comment by JourneyOver** [comment]
@Firegodd take a look at 5.5.14, it runs a hell of a lot better now in battlegrounds. I no longer experience a fps drop while running battlegrounds myself now and fps is just better in general it seems.

**Comment by Firegodd** [comment]
@siweia Thank you very much for fixing this issue! Really Love your UI. I will be donating to your cause for sure. @JourneyOver Thank you I will and thank you for helping out with the fix.
