### ISSUE TITLE
In-Game Profiles

### ISSUE THREAD

**Issue by DavidRosseljong** [siweia/NDui#73]
Hello,

is it possible to use profiles for the ui in the future? :) That would be so easy to switch to different in no time.

Cheers :)

**Comment by siweia** [comment]
I don't like to use Ace lib to generate all these GUI stuff. It should be a huge work for me to write the whole structure.
Honestly, it is beyond my power atm.

**Comment by DavidRosseljong** [comment]
Alright, no problem. Glad you keep it up to date 👍
