### ISSUE TITLE
给动作条渐隐功能添加更多条件后怎么注册相应的事件呢，求指导？

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#81]
修改这个 [function](https://github.com/siweia/NDui/blob/7ab8565756819fd3000a35c76e00ed9a95529b6d/Interface/AddOns/NDui/Modules/ActionBar/Bars/Fader.lua#L59)

```
function IsMouseOverFrame(frame)
	if UnitExists("target") then return end
	if InCombatLockdown() then return end

	if MouseIsOver(frame) then return true end
	if not SpellFlyout:IsShown() then return false end
	if not SpellFlyout.__faderParent then return false end
	if SpellFlyout.__faderParent == frame and MouseIsOver(SpellFlyout) then return true end
	return false
end
```

比如说改成这样，加入了两个条件，当前有目标或者进入战斗则显示动作条，但是相应的事件该怎么注册呢，注册给这个 bar 的 frame 无效

```
local frame = CreateFrame("Frame", "NDui_ActionBar1", UIParent, "SecureHandlerStateTemplate")
frame:RegisterEvent('PLAYER_REGEN_ENABLED')
frame:RegisterEvent('PLAYER_REGEN_DISABLED')
frame:RegisterEvent('PLAYER_TARGET_CHANGED')
```
注册给 CreateBar2() 这个 function 有效，但是触发战斗时会报错

```
F:RegisterEvent('PLAYER_REGEN_ENABLED', CreateBar2())
F:RegisterEvent('PLAYER_REGEN_DISABLED', CreateBar2())
F:RegisterEvent('PLAYER_TARGET_CHANGED', CreateBar2())
```
研究了半天没搞懂，求指导 🤕

**Comment by siweia** [comment]
去fader里面改。

**Comment by siweia** [comment]
不会的话，就改statedriver比较简单。
https://github.com/zorker/rothui/blob/master/wow8.0/rActionBar_Zork/layout.lua#L88

**Comment by Solor** [comment]
statedriver我会用，但是它是直接显示和隐藏的，没有fadein和fadeout的动画 🤕

**Comment by Solor** [comment]
我现在就是在fader里修改的，但是不明白怎么给fader里的function注册事件
我觉得大概应该给这个[function](https://github.com/siweia/NDui/blob/7ab8565756819fd3000a35c76e00ed9a95529b6d/Interface/AddOns/NDui/Modules/ActionBar/Bars/Fader.lua#L59)注册事件，每次事件触发则更新一次这个function
但是我写成这样却无效还报错 🥱 
```
F:RegisterEvent('PLAYER_REGEN_ENABLED', IsMouseOverFrame)
F:RegisterEvent('PLAYER_REGEN_DISABLED', IsMouseOverFrame)
F:RegisterEvent('PLAYER_TARGET_CHANGED', IsMouseOverFrame)
```

**Comment by siweia** [comment]
肯定不能这样啊。IsMouseOverFrame针对的是button，你直接这样写的话，button哪里来的。
举个例子

local buttonList = {}
local function UpdateFadeState()
    for _, button in pairs(buttonList) do
        IsMouseOverFrame(button)
    end
end
F:RegisterEvent('PLAYER_REGEN_ENABLED', UpdateFadeState)

你要做的，就是把你想要变化的都加入到这个buttonList，这个应该很简单吧

**Comment by siweia** [comment]
112开始改
`local extraFaderList = {}

function Bar:CreateButtonFrameFader(buttonList, faderConfig)
	CreateFrameFader(self, faderConfig)
	for _, button in next, buttonList do
		if not button.__faderParent then
			button.__faderParent = self
			button:HookScript("OnEnter", OffFrameHandler)
			button:HookScript("OnLeave", OffFrameHandler)

			tinsert(extraFaderList, button)
		end
	end
end

local function UpdateExtraFader()
	for _, button in pairs(extraFaderList) do
		IsMouseOverFrame(button)
	end
end
B:RegisterEvent("PLAYER_REGEN_ENABLED", UpdateExtraFader)
B:RegisterEvent("PLAYER_REGEN_DISABLED", UpdateExtraFader)
B:RegisterEvent("PLAYER_TARGET_CHANGED", UpdateExtraFader)`

然后是这里
`local function IsMouseOverFrame(frame)
	if UnitExists("target") then return true end
	if InCombatLockdown() then return true end

	if MouseIsOver(frame) then return true end
	if not SpellFlyout:IsShown() then return false end
	if not SpellFlyout.__faderParent then return false end
	if SpellFlyout.__faderParent == frame and MouseIsOver(SpellFlyout) then return true end
	return false
end`

**Comment by siweia** [comment]
搞定了的话，吱个声，我把内容都删了

**Comment by Solor** [comment]
抱歉，刚到家
我测试了一下，渐隐的效果实际是由 `CreateFrameFader(frame, faderConfig)` `bar:CreateButtonFrameFader(buttonList, faderConfig)` 这两个function里的 `OnEnter` `OnLeave` 来触发的
按照你的写法，`PLAYER_REGEN_ENABLED`触发以后仍然要再触发一次 `OnEnter` `OnLeave` 才能让动作条fadein和fadeout，这样只符合mouseover判断显隐的状况，如果要做到有当前目标或者进入战斗判断就不行了

**Comment by siweia** [comment]
for _, button in pairs(extraFaderList) do
		OffFrameHandler(button)
	end
改成这样就可以了吧，前面没细看

**Comment by siweia** [comment]
你都知道是onenter触发了，你就把触发的function改由事件就好了。前面IsMouseOverFrame只是判断，还没有变化那一步。这样改应该就没问题了

**Comment by Solor** [comment]
是的，这样触发就正常了，这个过程太复杂了，我完全搞不懂哈哈 
感谢指导 😆

**Comment by siweia** [comment]
不想其他人看到这段，然后乱改
