### ISSUE TITLE
Drop FPS in bag

### ISSUE THREAD

**Issue by Kbldmon92** [siweia/NDui#82]
firstly I'd like to thank you for this amazing addon.
Although I have been plagued by a strange problem.
Whenever I mouseover an item in my bags window i get big fps drop / stutter.

**Comment by siweia** [comment]
Disable your addon like bagsync etc.

**Comment by Kbldmon92** [comment]
All addons disable, only NDui

**Comment by siweia** [comment]
It is normal, it happens even you have all addons disabled.
Which only occurs when mouseover gear items.
