### ISSUE TITLE
稀有警报能否在特定地图禁用？

### ISSUE THREAD

**Issue by Solor** [siweia/NDui#9]
比如 wod 版本的要塞每次都提示箱子
涌泉战场一直提示资源点
这些地图应该加入黑名单禁用警报

**Comment by Solor** [comment]
另外经验条在人物满级神器退役并且没有勾选监视声望的情况下应该隐藏。

**Comment by siweia** [comment]
经验条常驻是为了点击看神器页面的
黑名单你可以提供一些ID吗

**Comment by Solor** [comment]
971 976 这两个是 wod 版本的要塞，联盟和部落
涌泉海滩战场等我下次排到了再看下 mapid

**Comment by Solor** [comment]
涌泉海滩战场 1803

**Comment by siweia** [comment]
你这个是什么ID？不是mapID也不是instanceID
