### ISSUE TITLE
Details bars on 1440p 

### ISSUE THREAD

**Issue by imbaVillain** [siweia/NDui#91]
Have bought a new monitor 1440p and everything works fine, except for Details only displaying 4 bars in second window while first window displays 5 like normal: https://imgur.com/fEcvbrU

Tried clean installs, profile resets and different UI scaling but no luck. Know how to fix?
Experience this on both Retail and Beta (v9).

**Comment by siweia** [comment]
https://github.com/siweia/NDui/blob/012cfb66437b0afa46b45355bf3cf00225370d0a/Interface/AddOns/NDui/Modules/Skins/AddOns/Details.lua#L83

Try to increase the height at here.
Or manually resize your second window.

**Comment by imbaVillain** [comment]
Changing it to 96 fixed this. Thank you!
