### ISSUE TITLE
Covenant minimap button overlaps with clock in v10

### ISSUE THREAD

**Issue by imbaVillain** [siweia/NDui#92]
https://imgur.com/OtjeneP

**Comment by siweia** [comment]
ebed15f14c20aa2b8762124e44c4827935ef6801
Should have fixed here.

**Comment by imbaVillain** [comment]
That fixes the clock icon to bottom right but the covenant is still overlapping.

**Comment by siweia** [comment]
Don't you know the clock icon always presents as the garrison system, there isn't a "overlay issue".
Covenant is your new garrison in 9.0.

**Comment by imbaVillain** [comment]
Yes I know that, but the covenant symbol was stuck permanently like below. UI reset fixed it anyway. 

![image](https://user-images.githubusercontent.com/67341080/88968248-fbda1900-d2a6-11ea-96b4-4332985d8f2c.png)

**Comment by siweia** [comment]
If you are talking about its glowing textue, that's normal as well.
I didn't change the textue even on bfa.

**Comment by imbaVillain** [comment]
No it was not glowing anymore, just stuck - like in the picture - even without active/completed missions. 
Probably was a bug in the game and not the ui because it was fine after a reset. 
Thanks for fixing the clock position.
