### ISSUE TITLE
Lua error in dungeons (DBM)

### ISSUE THREAD

**Issue by imbaVillain** [siweia/NDui#93]
Version 5.9.0

AddOns\DBM-Core\DBM-Core.lua:6481: attempt to compare number with nil
Count: 2

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\DBM-Core\DBM-Core.lua"]:6481: in function <AddOns\DBM-Core\DBM-Core.lua:6480>
[string "@AddOns\DBM-Core\DBM-Core.lua"]:6489: in function `StartLogging'
[string "@AddOns\DBM-Core\DBM-Core.lua"]:4022: in function `func'
[string "@AddOns\DBM-Core\DBM-Core.lua"]:1818: in function <AddOns\DBM-Core\DBM-Core.lua:1809>

**Comment by siweia** [comment]
The error is from DBM, why do you open an issue here?

**Comment by imbaVillain** [comment]
Never happened in v5.8... Assumed it was caused by the ui.. sorry mate
