### ISSUE TITLE
[Feature Bags] Show Locked/Unuseable Gear/Items

### ISSUE THREAD

**Issue by Kkthnx** [siweia/NDui#94]
An idea to add function to the bags to show it an item is usable or not or or your level? So in theory if you are level 98 and you have gear in your bags that is 99 the item texture slow icon should be red indicating that the item/armor is not able to be used because the level is not met or the item is locked.

There is a lib that refers to this.
https://github.com/Jaliborc/Unfit-1.0

**Comment by Kkthnx** [comment]
This would be the code we can use

`-- Determine if we can use that item or not?
if (Unfit:IsItemUnusable(item.id) or item.minLevel and item.minLevel > UnitLevel("player")) and not item.locked then
	_G[self:GetName().."IconTexture"]:SetVertexColor(1, 0.1, 0.1)
else
	_G[self:GetName().."IconTexture"]:SetVertexColor(1, 1, 1)
end`

Obviously we are using the lib here for such. Anyways just an idea for a feature.

**Comment by siweia** [comment]
I don't like to use any extra libs unless I have to, and not really interested about this feature.
You can add this for your own.

**Comment by Kkthnx** [comment]
Thanks for the reply! Keep up the good work!
